package com.topline.model;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccCodeIsNull() {
            addCriterion("acc_code is null");
            return (Criteria) this;
        }

        public Criteria andAccCodeIsNotNull() {
            addCriterion("acc_code is not null");
            return (Criteria) this;
        }

        public Criteria andAccCodeEqualTo(Integer value) {
            addCriterion("acc_code =", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeNotEqualTo(Integer value) {
            addCriterion("acc_code <>", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeGreaterThan(Integer value) {
            addCriterion("acc_code >", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("acc_code >=", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeLessThan(Integer value) {
            addCriterion("acc_code <", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeLessThanOrEqualTo(Integer value) {
            addCriterion("acc_code <=", value, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeIn(List<Integer> values) {
            addCriterion("acc_code in", values, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeNotIn(List<Integer> values) {
            addCriterion("acc_code not in", values, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeBetween(Integer value1, Integer value2) {
            addCriterion("acc_code between", value1, value2, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("acc_code not between", value1, value2, "accCode");
            return (Criteria) this;
        }

        public Criteria andAccNameIsNull() {
            addCriterion("acc_name is null");
            return (Criteria) this;
        }

        public Criteria andAccNameIsNotNull() {
            addCriterion("acc_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccNameEqualTo(String value) {
            addCriterion("acc_name =", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotEqualTo(String value) {
            addCriterion("acc_name <>", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameGreaterThan(String value) {
            addCriterion("acc_name >", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameGreaterThanOrEqualTo(String value) {
            addCriterion("acc_name >=", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLessThan(String value) {
            addCriterion("acc_name <", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLessThanOrEqualTo(String value) {
            addCriterion("acc_name <=", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLike(String value) {
            addCriterion("acc_name like", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotLike(String value) {
            addCriterion("acc_name not like", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameIn(List<String> values) {
            addCriterion("acc_name in", values, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotIn(List<String> values) {
            addCriterion("acc_name not in", values, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameBetween(String value1, String value2) {
            addCriterion("acc_name between", value1, value2, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotBetween(String value1, String value2) {
            addCriterion("acc_name not between", value1, value2, "accName");
            return (Criteria) this;
        }

        public Criteria andAccTypeIsNull() {
            addCriterion("acc_type is null");
            return (Criteria) this;
        }

        public Criteria andAccTypeIsNotNull() {
            addCriterion("acc_type is not null");
            return (Criteria) this;
        }

        public Criteria andAccTypeEqualTo(String value) {
            addCriterion("acc_type =", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeNotEqualTo(String value) {
            addCriterion("acc_type <>", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeGreaterThan(String value) {
            addCriterion("acc_type >", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeGreaterThanOrEqualTo(String value) {
            addCriterion("acc_type >=", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeLessThan(String value) {
            addCriterion("acc_type <", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeLessThanOrEqualTo(String value) {
            addCriterion("acc_type <=", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeLike(String value) {
            addCriterion("acc_type like", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeNotLike(String value) {
            addCriterion("acc_type not like", value, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeIn(List<String> values) {
            addCriterion("acc_type in", values, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeNotIn(List<String> values) {
            addCriterion("acc_type not in", values, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeBetween(String value1, String value2) {
            addCriterion("acc_type between", value1, value2, "accType");
            return (Criteria) this;
        }

        public Criteria andAccTypeNotBetween(String value1, String value2) {
            addCriterion("acc_type not between", value1, value2, "accType");
            return (Criteria) this;
        }

        public Criteria andAccAddressIsNull() {
            addCriterion("acc_address is null");
            return (Criteria) this;
        }

        public Criteria andAccAddressIsNotNull() {
            addCriterion("acc_address is not null");
            return (Criteria) this;
        }

        public Criteria andAccAddressEqualTo(String value) {
            addCriterion("acc_address =", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressNotEqualTo(String value) {
            addCriterion("acc_address <>", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressGreaterThan(String value) {
            addCriterion("acc_address >", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressGreaterThanOrEqualTo(String value) {
            addCriterion("acc_address >=", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressLessThan(String value) {
            addCriterion("acc_address <", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressLessThanOrEqualTo(String value) {
            addCriterion("acc_address <=", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressLike(String value) {
            addCriterion("acc_address like", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressNotLike(String value) {
            addCriterion("acc_address not like", value, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressIn(List<String> values) {
            addCriterion("acc_address in", values, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressNotIn(List<String> values) {
            addCriterion("acc_address not in", values, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressBetween(String value1, String value2) {
            addCriterion("acc_address between", value1, value2, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccAddressNotBetween(String value1, String value2) {
            addCriterion("acc_address not between", value1, value2, "accAddress");
            return (Criteria) this;
        }

        public Criteria andAccLocationIsNull() {
            addCriterion("acc_location is null");
            return (Criteria) this;
        }

        public Criteria andAccLocationIsNotNull() {
            addCriterion("acc_location is not null");
            return (Criteria) this;
        }

        public Criteria andAccLocationEqualTo(String value) {
            addCriterion("acc_location =", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationNotEqualTo(String value) {
            addCriterion("acc_location <>", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationGreaterThan(String value) {
            addCriterion("acc_location >", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationGreaterThanOrEqualTo(String value) {
            addCriterion("acc_location >=", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationLessThan(String value) {
            addCriterion("acc_location <", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationLessThanOrEqualTo(String value) {
            addCriterion("acc_location <=", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationLike(String value) {
            addCriterion("acc_location like", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationNotLike(String value) {
            addCriterion("acc_location not like", value, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationIn(List<String> values) {
            addCriterion("acc_location in", values, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationNotIn(List<String> values) {
            addCriterion("acc_location not in", values, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationBetween(String value1, String value2) {
            addCriterion("acc_location between", value1, value2, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccLocationNotBetween(String value1, String value2) {
            addCriterion("acc_location not between", value1, value2, "accLocation");
            return (Criteria) this;
        }

        public Criteria andAccEmailIsNull() {
            addCriterion("acc_email is null");
            return (Criteria) this;
        }

        public Criteria andAccEmailIsNotNull() {
            addCriterion("acc_email is not null");
            return (Criteria) this;
        }

        public Criteria andAccEmailEqualTo(String value) {
            addCriterion("acc_email =", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailNotEqualTo(String value) {
            addCriterion("acc_email <>", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailGreaterThan(String value) {
            addCriterion("acc_email >", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailGreaterThanOrEqualTo(String value) {
            addCriterion("acc_email >=", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailLessThan(String value) {
            addCriterion("acc_email <", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailLessThanOrEqualTo(String value) {
            addCriterion("acc_email <=", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailLike(String value) {
            addCriterion("acc_email like", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailNotLike(String value) {
            addCriterion("acc_email not like", value, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailIn(List<String> values) {
            addCriterion("acc_email in", values, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailNotIn(List<String> values) {
            addCriterion("acc_email not in", values, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailBetween(String value1, String value2) {
            addCriterion("acc_email between", value1, value2, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccEmailNotBetween(String value1, String value2) {
            addCriterion("acc_email not between", value1, value2, "accEmail");
            return (Criteria) this;
        }

        public Criteria andAccFaxIsNull() {
            addCriterion("acc_fax is null");
            return (Criteria) this;
        }

        public Criteria andAccFaxIsNotNull() {
            addCriterion("acc_fax is not null");
            return (Criteria) this;
        }

        public Criteria andAccFaxEqualTo(String value) {
            addCriterion("acc_fax =", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxNotEqualTo(String value) {
            addCriterion("acc_fax <>", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxGreaterThan(String value) {
            addCriterion("acc_fax >", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxGreaterThanOrEqualTo(String value) {
            addCriterion("acc_fax >=", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxLessThan(String value) {
            addCriterion("acc_fax <", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxLessThanOrEqualTo(String value) {
            addCriterion("acc_fax <=", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxLike(String value) {
            addCriterion("acc_fax like", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxNotLike(String value) {
            addCriterion("acc_fax not like", value, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxIn(List<String> values) {
            addCriterion("acc_fax in", values, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxNotIn(List<String> values) {
            addCriterion("acc_fax not in", values, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxBetween(String value1, String value2) {
            addCriterion("acc_fax between", value1, value2, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccFaxNotBetween(String value1, String value2) {
            addCriterion("acc_fax not between", value1, value2, "accFax");
            return (Criteria) this;
        }

        public Criteria andAccTelNoIsNull() {
            addCriterion("acc_tel_no is null");
            return (Criteria) this;
        }

        public Criteria andAccTelNoIsNotNull() {
            addCriterion("acc_tel_no is not null");
            return (Criteria) this;
        }

        public Criteria andAccTelNoEqualTo(String value) {
            addCriterion("acc_tel_no =", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoNotEqualTo(String value) {
            addCriterion("acc_tel_no <>", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoGreaterThan(String value) {
            addCriterion("acc_tel_no >", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("acc_tel_no >=", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoLessThan(String value) {
            addCriterion("acc_tel_no <", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoLessThanOrEqualTo(String value) {
            addCriterion("acc_tel_no <=", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoLike(String value) {
            addCriterion("acc_tel_no like", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoNotLike(String value) {
            addCriterion("acc_tel_no not like", value, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoIn(List<String> values) {
            addCriterion("acc_tel_no in", values, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoNotIn(List<String> values) {
            addCriterion("acc_tel_no not in", values, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoBetween(String value1, String value2) {
            addCriterion("acc_tel_no between", value1, value2, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccTelNoNotBetween(String value1, String value2) {
            addCriterion("acc_tel_no not between", value1, value2, "accTelNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoIsNull() {
            addCriterion("acc_mobile_no is null");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoIsNotNull() {
            addCriterion("acc_mobile_no is not null");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoEqualTo(String value) {
            addCriterion("acc_mobile_no =", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoNotEqualTo(String value) {
            addCriterion("acc_mobile_no <>", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoGreaterThan(String value) {
            addCriterion("acc_mobile_no >", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("acc_mobile_no >=", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoLessThan(String value) {
            addCriterion("acc_mobile_no <", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoLessThanOrEqualTo(String value) {
            addCriterion("acc_mobile_no <=", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoLike(String value) {
            addCriterion("acc_mobile_no like", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoNotLike(String value) {
            addCriterion("acc_mobile_no not like", value, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoIn(List<String> values) {
            addCriterion("acc_mobile_no in", values, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoNotIn(List<String> values) {
            addCriterion("acc_mobile_no not in", values, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoBetween(String value1, String value2) {
            addCriterion("acc_mobile_no between", value1, value2, "accMobileNo");
            return (Criteria) this;
        }

        public Criteria andAccMobileNoNotBetween(String value1, String value2) {
            addCriterion("acc_mobile_no not between", value1, value2, "accMobileNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_accounts
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 24 21:41:34 EAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}