package com.topline.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ApprovalAreaDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public ApprovalAreaDtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAppvdCodeIsNull() {
            addCriterion("appvd_code is null");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeIsNotNull() {
            addCriterion("appvd_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeEqualTo(Integer value) {
            addCriterion("appvd_code =", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeNotEqualTo(Integer value) {
            addCriterion("appvd_code <>", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeGreaterThan(Integer value) {
            addCriterion("appvd_code >", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("appvd_code >=", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeLessThan(Integer value) {
            addCriterion("appvd_code <", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeLessThanOrEqualTo(Integer value) {
            addCriterion("appvd_code <=", value, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeIn(List<Integer> values) {
            addCriterion("appvd_code in", values, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeNotIn(List<Integer> values) {
            addCriterion("appvd_code not in", values, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeBetween(Integer value1, Integer value2) {
            addCriterion("appvd_code between", value1, value2, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("appvd_code not between", value1, value2, "appvdCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeIsNull() {
            addCriterion("appvd_appv_code is null");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeIsNotNull() {
            addCriterion("appvd_appv_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeEqualTo(Integer value) {
            addCriterion("appvd_appv_code =", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeNotEqualTo(Integer value) {
            addCriterion("appvd_appv_code <>", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeGreaterThan(Integer value) {
            addCriterion("appvd_appv_code >", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("appvd_appv_code >=", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeLessThan(Integer value) {
            addCriterion("appvd_appv_code <", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeLessThanOrEqualTo(Integer value) {
            addCriterion("appvd_appv_code <=", value, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeIn(List<Integer> values) {
            addCriterion("appvd_appv_code in", values, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeNotIn(List<Integer> values) {
            addCriterion("appvd_appv_code not in", values, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeBetween(Integer value1, Integer value2) {
            addCriterion("appvd_appv_code between", value1, value2, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdAppvCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("appvd_appv_code not between", value1, value2, "appvdAppvCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeIsNull() {
            addCriterion("appvd_usr_code is null");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeIsNotNull() {
            addCriterion("appvd_usr_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeEqualTo(Integer value) {
            addCriterion("appvd_usr_code =", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeNotEqualTo(Integer value) {
            addCriterion("appvd_usr_code <>", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeGreaterThan(Integer value) {
            addCriterion("appvd_usr_code >", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("appvd_usr_code >=", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeLessThan(Integer value) {
            addCriterion("appvd_usr_code <", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeLessThanOrEqualTo(Integer value) {
            addCriterion("appvd_usr_code <=", value, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeIn(List<Integer> values) {
            addCriterion("appvd_usr_code in", values, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeNotIn(List<Integer> values) {
            addCriterion("appvd_usr_code not in", values, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeBetween(Integer value1, Integer value2) {
            addCriterion("appvd_usr_code between", value1, value2, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdUsrCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("appvd_usr_code not between", value1, value2, "appvdUsrCode");
            return (Criteria) this;
        }

        public Criteria andAppvdWefIsNull() {
            addCriterion("appvd_wef is null");
            return (Criteria) this;
        }

        public Criteria andAppvdWefIsNotNull() {
            addCriterion("appvd_wef is not null");
            return (Criteria) this;
        }

        public Criteria andAppvdWefEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wef =", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefNotEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wef <>", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefGreaterThan(Date value) {
            addCriterionForJDBCDate("appvd_wef >", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wef >=", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefLessThan(Date value) {
            addCriterionForJDBCDate("appvd_wef <", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wef <=", value, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefIn(List<Date> values) {
            addCriterionForJDBCDate("appvd_wef in", values, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefNotIn(List<Date> values) {
            addCriterionForJDBCDate("appvd_wef not in", values, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appvd_wef between", value1, value2, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWefNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appvd_wef not between", value1, value2, "appvdWef");
            return (Criteria) this;
        }

        public Criteria andAppvdWetIsNull() {
            addCriterion("appvd_wet is null");
            return (Criteria) this;
        }

        public Criteria andAppvdWetIsNotNull() {
            addCriterion("appvd_wet is not null");
            return (Criteria) this;
        }

        public Criteria andAppvdWetEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wet =", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetNotEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wet <>", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetGreaterThan(Date value) {
            addCriterionForJDBCDate("appvd_wet >", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wet >=", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetLessThan(Date value) {
            addCriterionForJDBCDate("appvd_wet <", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appvd_wet <=", value, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetIn(List<Date> values) {
            addCriterionForJDBCDate("appvd_wet in", values, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetNotIn(List<Date> values) {
            addCriterionForJDBCDate("appvd_wet not in", values, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appvd_wet between", value1, value2, "appvdWet");
            return (Criteria) this;
        }

        public Criteria andAppvdWetNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appvd_wet not between", value1, value2, "appvdWet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 14 22:31:54 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}