package com.topline.model;

import java.util.Date;

public class ApprovalAreaDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_approval_dtls.appvd_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    private Integer appvdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_approval_dtls.appvd_appv_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    private Integer appvdAppvCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_approval_dtls.appvd_usr_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    private Integer appvdUsrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_approval_dtls.appvd_wef
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    private Date appvdWef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_approval_dtls.appvd_wet
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    private Date appvdWet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_approval_dtls.appvd_code
     *
     * @return the value of inv_approval_dtls.appvd_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Integer getAppvdCode() {
        return appvdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_approval_dtls.appvd_code
     *
     * @param appvdCode the value for inv_approval_dtls.appvd_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setAppvdCode(Integer appvdCode) {
        this.appvdCode = appvdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_approval_dtls.appvd_appv_code
     *
     * @return the value of inv_approval_dtls.appvd_appv_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Integer getAppvdAppvCode() {
        return appvdAppvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_approval_dtls.appvd_appv_code
     *
     * @param appvdAppvCode the value for inv_approval_dtls.appvd_appv_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setAppvdAppvCode(Integer appvdAppvCode) {
        this.appvdAppvCode = appvdAppvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_approval_dtls.appvd_usr_code
     *
     * @return the value of inv_approval_dtls.appvd_usr_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Integer getAppvdUsrCode() {
        return appvdUsrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_approval_dtls.appvd_usr_code
     *
     * @param appvdUsrCode the value for inv_approval_dtls.appvd_usr_code
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setAppvdUsrCode(Integer appvdUsrCode) {
        this.appvdUsrCode = appvdUsrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_approval_dtls.appvd_wef
     *
     * @return the value of inv_approval_dtls.appvd_wef
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Date getAppvdWef() {
        return appvdWef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_approval_dtls.appvd_wef
     *
     * @param appvdWef the value for inv_approval_dtls.appvd_wef
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setAppvdWef(Date appvdWef) {
        this.appvdWef = appvdWef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_approval_dtls.appvd_wet
     *
     * @return the value of inv_approval_dtls.appvd_wet
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public Date getAppvdWet() {
        return appvdWet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_approval_dtls.appvd_wet
     *
     * @param appvdWet the value for inv_approval_dtls.appvd_wet
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    public void setAppvdWet(Date appvdWet) {
        this.appvdWet = appvdWet;
    }
}