package com.topline.model;

import java.util.ArrayList;
import java.util.List;

public class CustomizeAreaDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public CustomizeAreaDtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCtadIdIsNull() {
            addCriterion("ctad_id is null");
            return (Criteria) this;
        }

        public Criteria andCtadIdIsNotNull() {
            addCriterion("ctad_id is not null");
            return (Criteria) this;
        }

        public Criteria andCtadIdEqualTo(Integer value) {
            addCriterion("ctad_id =", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdNotEqualTo(Integer value) {
            addCriterion("ctad_id <>", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdGreaterThan(Integer value) {
            addCriterion("ctad_id >", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ctad_id >=", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdLessThan(Integer value) {
            addCriterion("ctad_id <", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdLessThanOrEqualTo(Integer value) {
            addCriterion("ctad_id <=", value, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdIn(List<Integer> values) {
            addCriterion("ctad_id in", values, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdNotIn(List<Integer> values) {
            addCriterion("ctad_id not in", values, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdBetween(Integer value1, Integer value2) {
            addCriterion("ctad_id between", value1, value2, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ctad_id not between", value1, value2, "ctadId");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeIsNull() {
            addCriterion("ctad_cta_code is null");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeIsNotNull() {
            addCriterion("ctad_cta_code is not null");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeEqualTo(String value) {
            addCriterion("ctad_cta_code =", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeNotEqualTo(String value) {
            addCriterion("ctad_cta_code <>", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeGreaterThan(String value) {
            addCriterion("ctad_cta_code >", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ctad_cta_code >=", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeLessThan(String value) {
            addCriterion("ctad_cta_code <", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeLessThanOrEqualTo(String value) {
            addCriterion("ctad_cta_code <=", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeLike(String value) {
            addCriterion("ctad_cta_code like", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeNotLike(String value) {
            addCriterion("ctad_cta_code not like", value, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeIn(List<String> values) {
            addCriterion("ctad_cta_code in", values, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeNotIn(List<String> values) {
            addCriterion("ctad_cta_code not in", values, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeBetween(String value1, String value2) {
            addCriterion("ctad_cta_code between", value1, value2, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadCtaCodeNotBetween(String value1, String value2) {
            addCriterion("ctad_cta_code not between", value1, value2, "ctadCtaCode");
            return (Criteria) this;
        }

        public Criteria andCtadColumnIsNull() {
            addCriterion("ctad_column is null");
            return (Criteria) this;
        }

        public Criteria andCtadColumnIsNotNull() {
            addCriterion("ctad_column is not null");
            return (Criteria) this;
        }

        public Criteria andCtadColumnEqualTo(String value) {
            addCriterion("ctad_column =", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnNotEqualTo(String value) {
            addCriterion("ctad_column <>", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnGreaterThan(String value) {
            addCriterion("ctad_column >", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnGreaterThanOrEqualTo(String value) {
            addCriterion("ctad_column >=", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnLessThan(String value) {
            addCriterion("ctad_column <", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnLessThanOrEqualTo(String value) {
            addCriterion("ctad_column <=", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnLike(String value) {
            addCriterion("ctad_column like", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnNotLike(String value) {
            addCriterion("ctad_column not like", value, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnIn(List<String> values) {
            addCriterion("ctad_column in", values, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnNotIn(List<String> values) {
            addCriterion("ctad_column not in", values, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnBetween(String value1, String value2) {
            addCriterion("ctad_column between", value1, value2, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnNotBetween(String value1, String value2) {
            addCriterion("ctad_column not between", value1, value2, "ctadColumn");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescIsNull() {
            addCriterion("ctad_column_desc is null");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescIsNotNull() {
            addCriterion("ctad_column_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescEqualTo(String value) {
            addCriterion("ctad_column_desc =", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescNotEqualTo(String value) {
            addCriterion("ctad_column_desc <>", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescGreaterThan(String value) {
            addCriterion("ctad_column_desc >", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescGreaterThanOrEqualTo(String value) {
            addCriterion("ctad_column_desc >=", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescLessThan(String value) {
            addCriterion("ctad_column_desc <", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescLessThanOrEqualTo(String value) {
            addCriterion("ctad_column_desc <=", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescLike(String value) {
            addCriterion("ctad_column_desc like", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescNotLike(String value) {
            addCriterion("ctad_column_desc not like", value, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescIn(List<String> values) {
            addCriterion("ctad_column_desc in", values, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescNotIn(List<String> values) {
            addCriterion("ctad_column_desc not in", values, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescBetween(String value1, String value2) {
            addCriterion("ctad_column_desc between", value1, value2, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadColumnDescNotBetween(String value1, String value2) {
            addCriterion("ctad_column_desc not between", value1, value2, "ctadColumnDesc");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleIsNull() {
            addCriterion("ctad_isVisible is null");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleIsNotNull() {
            addCriterion("ctad_isVisible is not null");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleEqualTo(String value) {
            addCriterion("ctad_isVisible =", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleNotEqualTo(String value) {
            addCriterion("ctad_isVisible <>", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleGreaterThan(String value) {
            addCriterion("ctad_isVisible >", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleGreaterThanOrEqualTo(String value) {
            addCriterion("ctad_isVisible >=", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleLessThan(String value) {
            addCriterion("ctad_isVisible <", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleLessThanOrEqualTo(String value) {
            addCriterion("ctad_isVisible <=", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleLike(String value) {
            addCriterion("ctad_isVisible like", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleNotLike(String value) {
            addCriterion("ctad_isVisible not like", value, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleIn(List<String> values) {
            addCriterion("ctad_isVisible in", values, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleNotIn(List<String> values) {
            addCriterion("ctad_isVisible not in", values, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleBetween(String value1, String value2) {
            addCriterion("ctad_isVisible between", value1, value2, "ctadIsvisible");
            return (Criteria) this;
        }

        public Criteria andCtadIsvisibleNotBetween(String value1, String value2) {
            addCriterion("ctad_isVisible not between", value1, value2, "ctadIsvisible");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 19:27:13 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}