package com.topline.model;

import java.util.ArrayList;
import java.util.List;

public class CustomizeAreaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public CustomizeAreaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCtaCodeIsNull() {
            addCriterion("CTA_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCtaCodeIsNotNull() {
            addCriterion("CTA_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCtaCodeEqualTo(String value) {
            addCriterion("CTA_CODE =", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeNotEqualTo(String value) {
            addCriterion("CTA_CODE <>", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeGreaterThan(String value) {
            addCriterion("CTA_CODE >", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CTA_CODE >=", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeLessThan(String value) {
            addCriterion("CTA_CODE <", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeLessThanOrEqualTo(String value) {
            addCriterion("CTA_CODE <=", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeLike(String value) {
            addCriterion("CTA_CODE like", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeNotLike(String value) {
            addCriterion("CTA_CODE not like", value, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeIn(List<String> values) {
            addCriterion("CTA_CODE in", values, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeNotIn(List<String> values) {
            addCriterion("CTA_CODE not in", values, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeBetween(String value1, String value2) {
            addCriterion("CTA_CODE between", value1, value2, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaCodeNotBetween(String value1, String value2) {
            addCriterion("CTA_CODE not between", value1, value2, "ctaCode");
            return (Criteria) this;
        }

        public Criteria andCtaNameIsNull() {
            addCriterion("CTA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCtaNameIsNotNull() {
            addCriterion("CTA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCtaNameEqualTo(String value) {
            addCriterion("CTA_NAME =", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameNotEqualTo(String value) {
            addCriterion("CTA_NAME <>", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameGreaterThan(String value) {
            addCriterion("CTA_NAME >", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameGreaterThanOrEqualTo(String value) {
            addCriterion("CTA_NAME >=", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameLessThan(String value) {
            addCriterion("CTA_NAME <", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameLessThanOrEqualTo(String value) {
            addCriterion("CTA_NAME <=", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameLike(String value) {
            addCriterion("CTA_NAME like", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameNotLike(String value) {
            addCriterion("CTA_NAME not like", value, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameIn(List<String> values) {
            addCriterion("CTA_NAME in", values, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameNotIn(List<String> values) {
            addCriterion("CTA_NAME not in", values, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameBetween(String value1, String value2) {
            addCriterion("CTA_NAME between", value1, value2, "ctaName");
            return (Criteria) this;
        }

        public Criteria andCtaNameNotBetween(String value1, String value2) {
            addCriterion("CTA_NAME not between", value1, value2, "ctaName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas
     *
     * @mbggenerated do_not_delete_during_merge Fri May 13 19:27:13 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}