package com.topline.model;

public class CustomizeArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_customize_areas.CTA_CODE
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    private String ctaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_customize_areas.CTA_NAME
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    private String ctaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_customize_areas.CTA_CODE
     *
     * @return the value of inv_customize_areas.CTA_CODE
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public String getCtaCode() {
        return ctaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_customize_areas.CTA_CODE
     *
     * @param ctaCode the value for inv_customize_areas.CTA_CODE
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setCtaCode(String ctaCode) {
        this.ctaCode = ctaCode == null ? null : ctaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_customize_areas.CTA_NAME
     *
     * @return the value of inv_customize_areas.CTA_NAME
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public String getCtaName() {
        return ctaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_customize_areas.CTA_NAME
     *
     * @param ctaName the value for inv_customize_areas.CTA_NAME
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    public void setCtaName(String ctaName) {
        this.ctaName = ctaName == null ? null : ctaName.trim();
    }
}