package com.topline.model;

import java.util.Date;

public class ItemReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_id
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private Integer rtnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_date
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private Date rtnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_acc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private Integer rtnAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_status
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private String rtnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_captured_by
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private String rtnCapturedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_captured_on
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private Date rtnCapturedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_returns.rtn_loc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    private Integer rtnLocCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_id
     *
     * @return the value of inv_returns.rtn_id
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public Integer getRtnId() {
        return rtnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_id
     *
     * @param rtnId the value for inv_returns.rtn_id
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnId(Integer rtnId) {
        this.rtnId = rtnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_date
     *
     * @return the value of inv_returns.rtn_date
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public Date getRtnDate() {
        return rtnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_date
     *
     * @param rtnDate the value for inv_returns.rtn_date
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnDate(Date rtnDate) {
        this.rtnDate = rtnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_acc_code
     *
     * @return the value of inv_returns.rtn_acc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public Integer getRtnAccCode() {
        return rtnAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_acc_code
     *
     * @param rtnAccCode the value for inv_returns.rtn_acc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnAccCode(Integer rtnAccCode) {
        this.rtnAccCode = rtnAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_status
     *
     * @return the value of inv_returns.rtn_status
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public String getRtnStatus() {
        return rtnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_status
     *
     * @param rtnStatus the value for inv_returns.rtn_status
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnStatus(String rtnStatus) {
        this.rtnStatus = rtnStatus == null ? null : rtnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_captured_by
     *
     * @return the value of inv_returns.rtn_captured_by
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public String getRtnCapturedBy() {
        return rtnCapturedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_captured_by
     *
     * @param rtnCapturedBy the value for inv_returns.rtn_captured_by
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnCapturedBy(String rtnCapturedBy) {
        this.rtnCapturedBy = rtnCapturedBy == null ? null : rtnCapturedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_captured_on
     *
     * @return the value of inv_returns.rtn_captured_on
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public Date getRtnCapturedOn() {
        return rtnCapturedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_captured_on
     *
     * @param rtnCapturedOn the value for inv_returns.rtn_captured_on
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnCapturedOn(Date rtnCapturedOn) {
        this.rtnCapturedOn = rtnCapturedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_returns.rtn_loc_code
     *
     * @return the value of inv_returns.rtn_loc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public Integer getRtnLocCode() {
        return rtnLocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_returns.rtn_loc_code
     *
     * @param rtnLocCode the value for inv_returns.rtn_loc_code
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    public void setRtnLocCode(Integer rtnLocCode) {
        this.rtnLocCode = rtnLocCode;
    }
}