package com.topline.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ItemReturnDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public ItemReturnDtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRtndIdIsNull() {
            addCriterion("rtnd_id is null");
            return (Criteria) this;
        }

        public Criteria andRtndIdIsNotNull() {
            addCriterion("rtnd_id is not null");
            return (Criteria) this;
        }

        public Criteria andRtndIdEqualTo(Integer value) {
            addCriterion("rtnd_id =", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdNotEqualTo(Integer value) {
            addCriterion("rtnd_id <>", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdGreaterThan(Integer value) {
            addCriterion("rtnd_id >", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rtnd_id >=", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdLessThan(Integer value) {
            addCriterion("rtnd_id <", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdLessThanOrEqualTo(Integer value) {
            addCriterion("rtnd_id <=", value, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdIn(List<Integer> values) {
            addCriterion("rtnd_id in", values, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdNotIn(List<Integer> values) {
            addCriterion("rtnd_id not in", values, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_id between", value1, value2, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_id not between", value1, value2, "rtndId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdIsNull() {
            addCriterion("rtnd_rtn_id is null");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdIsNotNull() {
            addCriterion("rtnd_rtn_id is not null");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdEqualTo(Integer value) {
            addCriterion("rtnd_rtn_id =", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdNotEqualTo(Integer value) {
            addCriterion("rtnd_rtn_id <>", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdGreaterThan(Integer value) {
            addCriterion("rtnd_rtn_id >", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rtnd_rtn_id >=", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdLessThan(Integer value) {
            addCriterion("rtnd_rtn_id <", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdLessThanOrEqualTo(Integer value) {
            addCriterion("rtnd_rtn_id <=", value, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdIn(List<Integer> values) {
            addCriterion("rtnd_rtn_id in", values, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdNotIn(List<Integer> values) {
            addCriterion("rtnd_rtn_id not in", values, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_rtn_id between", value1, value2, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndRtnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_rtn_id not between", value1, value2, "rtndRtnId");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeIsNull() {
            addCriterion("rtnd_pdt_code is null");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeIsNotNull() {
            addCriterion("rtnd_pdt_code is not null");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeEqualTo(Integer value) {
            addCriterion("rtnd_pdt_code =", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeNotEqualTo(Integer value) {
            addCriterion("rtnd_pdt_code <>", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeGreaterThan(Integer value) {
            addCriterion("rtnd_pdt_code >", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rtnd_pdt_code >=", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeLessThan(Integer value) {
            addCriterion("rtnd_pdt_code <", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeLessThanOrEqualTo(Integer value) {
            addCriterion("rtnd_pdt_code <=", value, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeIn(List<Integer> values) {
            addCriterion("rtnd_pdt_code in", values, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeNotIn(List<Integer> values) {
            addCriterion("rtnd_pdt_code not in", values, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_pdt_code between", value1, value2, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndPdtCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("rtnd_pdt_code not between", value1, value2, "rtndPdtCode");
            return (Criteria) this;
        }

        public Criteria andRtndQtyIsNull() {
            addCriterion("rtnd_qty is null");
            return (Criteria) this;
        }

        public Criteria andRtndQtyIsNotNull() {
            addCriterion("rtnd_qty is not null");
            return (Criteria) this;
        }

        public Criteria andRtndQtyEqualTo(Double value) {
            addCriterion("rtnd_qty =", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyNotEqualTo(Double value) {
            addCriterion("rtnd_qty <>", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyGreaterThan(Double value) {
            addCriterion("rtnd_qty >", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyGreaterThanOrEqualTo(Double value) {
            addCriterion("rtnd_qty >=", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyLessThan(Double value) {
            addCriterion("rtnd_qty <", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyLessThanOrEqualTo(Double value) {
            addCriterion("rtnd_qty <=", value, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyIn(List<Double> values) {
            addCriterion("rtnd_qty in", values, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyNotIn(List<Double> values) {
            addCriterion("rtnd_qty not in", values, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyBetween(Double value1, Double value2) {
            addCriterion("rtnd_qty between", value1, value2, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndQtyNotBetween(Double value1, Double value2) {
            addCriterion("rtnd_qty not between", value1, value2, "rtndQty");
            return (Criteria) this;
        }

        public Criteria andRtndPriceIsNull() {
            addCriterion("rtnd_price is null");
            return (Criteria) this;
        }

        public Criteria andRtndPriceIsNotNull() {
            addCriterion("rtnd_price is not null");
            return (Criteria) this;
        }

        public Criteria andRtndPriceEqualTo(BigDecimal value) {
            addCriterion("rtnd_price =", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceNotEqualTo(BigDecimal value) {
            addCriterion("rtnd_price <>", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceGreaterThan(BigDecimal value) {
            addCriterion("rtnd_price >", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rtnd_price >=", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceLessThan(BigDecimal value) {
            addCriterion("rtnd_price <", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rtnd_price <=", value, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceIn(List<BigDecimal> values) {
            addCriterion("rtnd_price in", values, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceNotIn(List<BigDecimal> values) {
            addCriterion("rtnd_price not in", values, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rtnd_price between", value1, value2, "rtndPrice");
            return (Criteria) this;
        }

        public Criteria andRtndPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rtnd_price not between", value1, value2, "rtndPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 01 16:35:05 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}