package com.topline.model;

public class ManAdjustmentDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_man_adjustment_dtls.madjd_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    private Integer madjdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_man_adjustment_dtls.madjd_madj_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    private Integer madjdMadjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_man_adjustment_dtls.madjd_pdt_code
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    private Integer madjdPdtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_man_adjustment_dtls.madjd_qty
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    private Double madjdQty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_man_adjustment_dtls.madjd_id
     *
     * @return the value of inv_man_adjustment_dtls.madjd_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public Integer getMadjdId() {
        return madjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_man_adjustment_dtls.madjd_id
     *
     * @param madjdId the value for inv_man_adjustment_dtls.madjd_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public void setMadjdId(Integer madjdId) {
        this.madjdId = madjdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_man_adjustment_dtls.madjd_madj_id
     *
     * @return the value of inv_man_adjustment_dtls.madjd_madj_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public Integer getMadjdMadjId() {
        return madjdMadjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_man_adjustment_dtls.madjd_madj_id
     *
     * @param madjdMadjId the value for inv_man_adjustment_dtls.madjd_madj_id
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public void setMadjdMadjId(Integer madjdMadjId) {
        this.madjdMadjId = madjdMadjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_man_adjustment_dtls.madjd_pdt_code
     *
     * @return the value of inv_man_adjustment_dtls.madjd_pdt_code
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public Integer getMadjdPdtCode() {
        return madjdPdtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_man_adjustment_dtls.madjd_pdt_code
     *
     * @param madjdPdtCode the value for inv_man_adjustment_dtls.madjd_pdt_code
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public void setMadjdPdtCode(Integer madjdPdtCode) {
        this.madjdPdtCode = madjdPdtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_man_adjustment_dtls.madjd_qty
     *
     * @return the value of inv_man_adjustment_dtls.madjd_qty
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public Double getMadjdQty() {
        return madjdQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_man_adjustment_dtls.madjd_qty
     *
     * @param madjdQty the value for inv_man_adjustment_dtls.madjd_qty
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    public void setMadjdQty(Double madjdQty) {
        this.madjdQty = madjdQty;
    }
}