package com.topline.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ManAdjustmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public ManAdjustmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMadjIdIsNull() {
            addCriterion("madj_id is null");
            return (Criteria) this;
        }

        public Criteria andMadjIdIsNotNull() {
            addCriterion("madj_id is not null");
            return (Criteria) this;
        }

        public Criteria andMadjIdEqualTo(Integer value) {
            addCriterion("madj_id =", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdNotEqualTo(Integer value) {
            addCriterion("madj_id <>", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdGreaterThan(Integer value) {
            addCriterion("madj_id >", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("madj_id >=", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdLessThan(Integer value) {
            addCriterion("madj_id <", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdLessThanOrEqualTo(Integer value) {
            addCriterion("madj_id <=", value, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdIn(List<Integer> values) {
            addCriterion("madj_id in", values, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdNotIn(List<Integer> values) {
            addCriterion("madj_id not in", values, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdBetween(Integer value1, Integer value2) {
            addCriterion("madj_id between", value1, value2, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("madj_id not between", value1, value2, "madjId");
            return (Criteria) this;
        }

        public Criteria andMadjDateIsNull() {
            addCriterion("madj_date is null");
            return (Criteria) this;
        }

        public Criteria andMadjDateIsNotNull() {
            addCriterion("madj_date is not null");
            return (Criteria) this;
        }

        public Criteria andMadjDateEqualTo(Date value) {
            addCriterionForJDBCDate("madj_date =", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("madj_date <>", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateGreaterThan(Date value) {
            addCriterionForJDBCDate("madj_date >", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("madj_date >=", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateLessThan(Date value) {
            addCriterionForJDBCDate("madj_date <", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("madj_date <=", value, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateIn(List<Date> values) {
            addCriterionForJDBCDate("madj_date in", values, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("madj_date not in", values, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("madj_date between", value1, value2, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("madj_date not between", value1, value2, "madjDate");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksIsNull() {
            addCriterion("madj_remarks is null");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksIsNotNull() {
            addCriterion("madj_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksEqualTo(String value) {
            addCriterion("madj_remarks =", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksNotEqualTo(String value) {
            addCriterion("madj_remarks <>", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksGreaterThan(String value) {
            addCriterion("madj_remarks >", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("madj_remarks >=", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksLessThan(String value) {
            addCriterion("madj_remarks <", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksLessThanOrEqualTo(String value) {
            addCriterion("madj_remarks <=", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksLike(String value) {
            addCriterion("madj_remarks like", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksNotLike(String value) {
            addCriterion("madj_remarks not like", value, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksIn(List<String> values) {
            addCriterion("madj_remarks in", values, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksNotIn(List<String> values) {
            addCriterion("madj_remarks not in", values, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksBetween(String value1, String value2) {
            addCriterion("madj_remarks between", value1, value2, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjRemarksNotBetween(String value1, String value2) {
            addCriterion("madj_remarks not between", value1, value2, "madjRemarks");
            return (Criteria) this;
        }

        public Criteria andMadjStatusIsNull() {
            addCriterion("madj_status is null");
            return (Criteria) this;
        }

        public Criteria andMadjStatusIsNotNull() {
            addCriterion("madj_status is not null");
            return (Criteria) this;
        }

        public Criteria andMadjStatusEqualTo(String value) {
            addCriterion("madj_status =", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusNotEqualTo(String value) {
            addCriterion("madj_status <>", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusGreaterThan(String value) {
            addCriterion("madj_status >", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusGreaterThanOrEqualTo(String value) {
            addCriterion("madj_status >=", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusLessThan(String value) {
            addCriterion("madj_status <", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusLessThanOrEqualTo(String value) {
            addCriterion("madj_status <=", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusLike(String value) {
            addCriterion("madj_status like", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusNotLike(String value) {
            addCriterion("madj_status not like", value, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusIn(List<String> values) {
            addCriterion("madj_status in", values, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusNotIn(List<String> values) {
            addCriterion("madj_status not in", values, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusBetween(String value1, String value2) {
            addCriterion("madj_status between", value1, value2, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjStatusNotBetween(String value1, String value2) {
            addCriterion("madj_status not between", value1, value2, "madjStatus");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByIsNull() {
            addCriterion("madj_captured_by is null");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByIsNotNull() {
            addCriterion("madj_captured_by is not null");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByEqualTo(String value) {
            addCriterion("madj_captured_by =", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByNotEqualTo(String value) {
            addCriterion("madj_captured_by <>", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByGreaterThan(String value) {
            addCriterion("madj_captured_by >", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByGreaterThanOrEqualTo(String value) {
            addCriterion("madj_captured_by >=", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByLessThan(String value) {
            addCriterion("madj_captured_by <", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByLessThanOrEqualTo(String value) {
            addCriterion("madj_captured_by <=", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByLike(String value) {
            addCriterion("madj_captured_by like", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByNotLike(String value) {
            addCriterion("madj_captured_by not like", value, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByIn(List<String> values) {
            addCriterion("madj_captured_by in", values, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByNotIn(List<String> values) {
            addCriterion("madj_captured_by not in", values, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByBetween(String value1, String value2) {
            addCriterion("madj_captured_by between", value1, value2, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedByNotBetween(String value1, String value2) {
            addCriterion("madj_captured_by not between", value1, value2, "madjCapturedBy");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnIsNull() {
            addCriterion("madj_captured_on is null");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnIsNotNull() {
            addCriterion("madj_captured_on is not null");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnEqualTo(Date value) {
            addCriterion("madj_captured_on =", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnNotEqualTo(Date value) {
            addCriterion("madj_captured_on <>", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnGreaterThan(Date value) {
            addCriterion("madj_captured_on >", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnGreaterThanOrEqualTo(Date value) {
            addCriterion("madj_captured_on >=", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnLessThan(Date value) {
            addCriterion("madj_captured_on <", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnLessThanOrEqualTo(Date value) {
            addCriterion("madj_captured_on <=", value, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnIn(List<Date> values) {
            addCriterion("madj_captured_on in", values, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnNotIn(List<Date> values) {
            addCriterion("madj_captured_on not in", values, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnBetween(Date value1, Date value2) {
            addCriterion("madj_captured_on between", value1, value2, "madjCapturedOn");
            return (Criteria) this;
        }

        public Criteria andMadjCapturedOnNotBetween(Date value1, Date value2) {
            addCriterion("madj_captured_on not between", value1, value2, "madjCapturedOn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 09 20:36:26 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_man_adjustments
     *
     * @mbggenerated Sat Apr 09 20:36:26 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}