package com.topline.model;

import java.math.BigDecimal;
import java.util.Date;

public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Integer pymtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_acc_code
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Integer pymtAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_date
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Date pymtDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private BigDecimal pymtAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_paymode
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private String pymtPaymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_paymemo
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private String pymtPaymemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_remarks
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private String pymtRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_captured_by
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private String pymtCapturedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payments.pymt_captured_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Date pymtCapturedOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_id
     *
     * @return the value of inv_payments.pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Integer getPymtId() {
        return pymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_id
     *
     * @param pymtId the value for inv_payments.pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtId(Integer pymtId) {
        this.pymtId = pymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_acc_code
     *
     * @return the value of inv_payments.pymt_acc_code
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Integer getPymtAccCode() {
        return pymtAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_acc_code
     *
     * @param pymtAccCode the value for inv_payments.pymt_acc_code
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtAccCode(Integer pymtAccCode) {
        this.pymtAccCode = pymtAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_date
     *
     * @return the value of inv_payments.pymt_date
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Date getPymtDate() {
        return pymtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_date
     *
     * @param pymtDate the value for inv_payments.pymt_date
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtDate(Date pymtDate) {
        this.pymtDate = pymtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_amount
     *
     * @return the value of inv_payments.pymt_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public BigDecimal getPymtAmount() {
        return pymtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_amount
     *
     * @param pymtAmount the value for inv_payments.pymt_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtAmount(BigDecimal pymtAmount) {
        this.pymtAmount = pymtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_paymode
     *
     * @return the value of inv_payments.pymt_paymode
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public String getPymtPaymode() {
        return pymtPaymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_paymode
     *
     * @param pymtPaymode the value for inv_payments.pymt_paymode
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtPaymode(String pymtPaymode) {
        this.pymtPaymode = pymtPaymode == null ? null : pymtPaymode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_paymemo
     *
     * @return the value of inv_payments.pymt_paymemo
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public String getPymtPaymemo() {
        return pymtPaymemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_paymemo
     *
     * @param pymtPaymemo the value for inv_payments.pymt_paymemo
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtPaymemo(String pymtPaymemo) {
        this.pymtPaymemo = pymtPaymemo == null ? null : pymtPaymemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_remarks
     *
     * @return the value of inv_payments.pymt_remarks
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public String getPymtRemarks() {
        return pymtRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_remarks
     *
     * @param pymtRemarks the value for inv_payments.pymt_remarks
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtRemarks(String pymtRemarks) {
        this.pymtRemarks = pymtRemarks == null ? null : pymtRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_captured_by
     *
     * @return the value of inv_payments.pymt_captured_by
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public String getPymtCapturedBy() {
        return pymtCapturedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_captured_by
     *
     * @param pymtCapturedBy the value for inv_payments.pymt_captured_by
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtCapturedBy(String pymtCapturedBy) {
        this.pymtCapturedBy = pymtCapturedBy == null ? null : pymtCapturedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payments.pymt_captured_on
     *
     * @return the value of inv_payments.pymt_captured_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Date getPymtCapturedOn() {
        return pymtCapturedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payments.pymt_captured_on
     *
     * @param pymtCapturedOn the value for inv_payments.pymt_captured_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtCapturedOn(Date pymtCapturedOn) {
        this.pymtCapturedOn = pymtCapturedOn;
    }
}