package com.topline.model;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payment_dtls.pymtd_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Integer pymtdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payment_dtls.pymtd_pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Integer pymtdPymtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payment_dtls.pymtd_pur_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Integer pymtdPurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payment_dtls.pymtd_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private BigDecimal pymtdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_payment_dtls.pymtd_updated_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    private Date pymtdUpdatedOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payment_dtls.pymtd_id
     *
     * @return the value of inv_payment_dtls.pymtd_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Integer getPymtdId() {
        return pymtdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payment_dtls.pymtd_id
     *
     * @param pymtdId the value for inv_payment_dtls.pymtd_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtdId(Integer pymtdId) {
        this.pymtdId = pymtdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payment_dtls.pymtd_pymt_id
     *
     * @return the value of inv_payment_dtls.pymtd_pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Integer getPymtdPymtId() {
        return pymtdPymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payment_dtls.pymtd_pymt_id
     *
     * @param pymtdPymtId the value for inv_payment_dtls.pymtd_pymt_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtdPymtId(Integer pymtdPymtId) {
        this.pymtdPymtId = pymtdPymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payment_dtls.pymtd_pur_id
     *
     * @return the value of inv_payment_dtls.pymtd_pur_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Integer getPymtdPurId() {
        return pymtdPurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payment_dtls.pymtd_pur_id
     *
     * @param pymtdPurId the value for inv_payment_dtls.pymtd_pur_id
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtdPurId(Integer pymtdPurId) {
        this.pymtdPurId = pymtdPurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payment_dtls.pymtd_amount
     *
     * @return the value of inv_payment_dtls.pymtd_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public BigDecimal getPymtdAmount() {
        return pymtdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payment_dtls.pymtd_amount
     *
     * @param pymtdAmount the value for inv_payment_dtls.pymtd_amount
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtdAmount(BigDecimal pymtdAmount) {
        this.pymtdAmount = pymtdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_payment_dtls.pymtd_updated_on
     *
     * @return the value of inv_payment_dtls.pymtd_updated_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public Date getPymtdUpdatedOn() {
        return pymtdUpdatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_payment_dtls.pymtd_updated_on
     *
     * @param pymtdUpdatedOn the value for inv_payment_dtls.pymtd_updated_on
     *
     * @mbggenerated Tue Jan 19 15:43:47 EAT 2016
     */
    public void setPymtdUpdatedOn(Date pymtdUpdatedOn) {
        this.pymtdUpdatedOn = pymtdUpdatedOn;
    }
}