package com.topline.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProductsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public ProductsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPdtCodeIsNull() {
            addCriterion("PDT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPdtCodeIsNotNull() {
            addCriterion("PDT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPdtCodeEqualTo(Integer value) {
            addCriterion("PDT_CODE =", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeNotEqualTo(Integer value) {
            addCriterion("PDT_CODE <>", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeGreaterThan(Integer value) {
            addCriterion("PDT_CODE >", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PDT_CODE >=", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeLessThan(Integer value) {
            addCriterion("PDT_CODE <", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PDT_CODE <=", value, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeIn(List<Integer> values) {
            addCriterion("PDT_CODE in", values, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeNotIn(List<Integer> values) {
            addCriterion("PDT_CODE not in", values, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeBetween(Integer value1, Integer value2) {
            addCriterion("PDT_CODE between", value1, value2, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PDT_CODE not between", value1, value2, "pdtCode");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescIsNull() {
            addCriterion("PDT_SHT_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescIsNotNull() {
            addCriterion("PDT_SHT_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescEqualTo(String value) {
            addCriterion("PDT_SHT_DESC =", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescNotEqualTo(String value) {
            addCriterion("PDT_SHT_DESC <>", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescGreaterThan(String value) {
            addCriterion("PDT_SHT_DESC >", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_SHT_DESC >=", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescLessThan(String value) {
            addCriterion("PDT_SHT_DESC <", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescLessThanOrEqualTo(String value) {
            addCriterion("PDT_SHT_DESC <=", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescLike(String value) {
            addCriterion("PDT_SHT_DESC like", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescNotLike(String value) {
            addCriterion("PDT_SHT_DESC not like", value, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescIn(List<String> values) {
            addCriterion("PDT_SHT_DESC in", values, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescNotIn(List<String> values) {
            addCriterion("PDT_SHT_DESC not in", values, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescBetween(String value1, String value2) {
            addCriterion("PDT_SHT_DESC between", value1, value2, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtShtDescNotBetween(String value1, String value2) {
            addCriterion("PDT_SHT_DESC not between", value1, value2, "pdtShtDesc");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionIsNull() {
            addCriterion("PDT_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionIsNotNull() {
            addCriterion("PDT_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionEqualTo(String value) {
            addCriterion("PDT_DESCRIPTION =", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionNotEqualTo(String value) {
            addCriterion("PDT_DESCRIPTION <>", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionGreaterThan(String value) {
            addCriterion("PDT_DESCRIPTION >", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_DESCRIPTION >=", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionLessThan(String value) {
            addCriterion("PDT_DESCRIPTION <", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionLessThanOrEqualTo(String value) {
            addCriterion("PDT_DESCRIPTION <=", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionLike(String value) {
            addCriterion("PDT_DESCRIPTION like", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionNotLike(String value) {
            addCriterion("PDT_DESCRIPTION not like", value, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionIn(List<String> values) {
            addCriterion("PDT_DESCRIPTION in", values, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionNotIn(List<String> values) {
            addCriterion("PDT_DESCRIPTION not in", values, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionBetween(String value1, String value2) {
            addCriterion("PDT_DESCRIPTION between", value1, value2, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtDescriptionNotBetween(String value1, String value2) {
            addCriterion("PDT_DESCRIPTION not between", value1, value2, "pdtDescription");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeIsNull() {
            addCriterion("PDT_LOC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeIsNotNull() {
            addCriterion("PDT_LOC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeEqualTo(Integer value) {
            addCriterion("PDT_LOC_CODE =", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeNotEqualTo(Integer value) {
            addCriterion("PDT_LOC_CODE <>", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeGreaterThan(Integer value) {
            addCriterion("PDT_LOC_CODE >", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PDT_LOC_CODE >=", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeLessThan(Integer value) {
            addCriterion("PDT_LOC_CODE <", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PDT_LOC_CODE <=", value, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeIn(List<Integer> values) {
            addCriterion("PDT_LOC_CODE in", values, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeNotIn(List<Integer> values) {
            addCriterion("PDT_LOC_CODE not in", values, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeBetween(Integer value1, Integer value2) {
            addCriterion("PDT_LOC_CODE between", value1, value2, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtLocCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PDT_LOC_CODE not between", value1, value2, "pdtLocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeIsNull() {
            addCriterion("PDT_SLOC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeIsNotNull() {
            addCriterion("PDT_SLOC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeEqualTo(Integer value) {
            addCriterion("PDT_SLOC_CODE =", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeNotEqualTo(Integer value) {
            addCriterion("PDT_SLOC_CODE <>", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeGreaterThan(Integer value) {
            addCriterion("PDT_SLOC_CODE >", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PDT_SLOC_CODE >=", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeLessThan(Integer value) {
            addCriterion("PDT_SLOC_CODE <", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PDT_SLOC_CODE <=", value, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeIn(List<Integer> values) {
            addCriterion("PDT_SLOC_CODE in", values, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeNotIn(List<Integer> values) {
            addCriterion("PDT_SLOC_CODE not in", values, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeBetween(Integer value1, Integer value2) {
            addCriterion("PDT_SLOC_CODE between", value1, value2, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtSlocCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PDT_SLOC_CODE not between", value1, value2, "pdtSlocCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeIsNull() {
            addCriterion("PDT_CAT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeIsNotNull() {
            addCriterion("PDT_CAT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeEqualTo(Integer value) {
            addCriterion("PDT_CAT_CODE =", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeNotEqualTo(Integer value) {
            addCriterion("PDT_CAT_CODE <>", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeGreaterThan(Integer value) {
            addCriterion("PDT_CAT_CODE >", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PDT_CAT_CODE >=", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeLessThan(Integer value) {
            addCriterion("PDT_CAT_CODE <", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PDT_CAT_CODE <=", value, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeIn(List<Integer> values) {
            addCriterion("PDT_CAT_CODE in", values, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeNotIn(List<Integer> values) {
            addCriterion("PDT_CAT_CODE not in", values, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeBetween(Integer value1, Integer value2) {
            addCriterion("PDT_CAT_CODE between", value1, value2, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtCatCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PDT_CAT_CODE not between", value1, value2, "pdtCatCode");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelIsNull() {
            addCriterion("PDT_MIN_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelIsNotNull() {
            addCriterion("PDT_MIN_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelEqualTo(Double value) {
            addCriterion("PDT_MIN_LEVEL =", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelNotEqualTo(Double value) {
            addCriterion("PDT_MIN_LEVEL <>", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelGreaterThan(Double value) {
            addCriterion("PDT_MIN_LEVEL >", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelGreaterThanOrEqualTo(Double value) {
            addCriterion("PDT_MIN_LEVEL >=", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelLessThan(Double value) {
            addCriterion("PDT_MIN_LEVEL <", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelLessThanOrEqualTo(Double value) {
            addCriterion("PDT_MIN_LEVEL <=", value, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelIn(List<Double> values) {
            addCriterion("PDT_MIN_LEVEL in", values, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelNotIn(List<Double> values) {
            addCriterion("PDT_MIN_LEVEL not in", values, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelBetween(Double value1, Double value2) {
            addCriterion("PDT_MIN_LEVEL between", value1, value2, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMinLevelNotBetween(Double value1, Double value2) {
            addCriterion("PDT_MIN_LEVEL not between", value1, value2, "pdtMinLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelIsNull() {
            addCriterion("PDT_MAX_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelIsNotNull() {
            addCriterion("PDT_MAX_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelEqualTo(Double value) {
            addCriterion("PDT_MAX_LEVEL =", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelNotEqualTo(Double value) {
            addCriterion("PDT_MAX_LEVEL <>", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelGreaterThan(Double value) {
            addCriterion("PDT_MAX_LEVEL >", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelGreaterThanOrEqualTo(Double value) {
            addCriterion("PDT_MAX_LEVEL >=", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelLessThan(Double value) {
            addCriterion("PDT_MAX_LEVEL <", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelLessThanOrEqualTo(Double value) {
            addCriterion("PDT_MAX_LEVEL <=", value, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelIn(List<Double> values) {
            addCriterion("PDT_MAX_LEVEL in", values, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelNotIn(List<Double> values) {
            addCriterion("PDT_MAX_LEVEL not in", values, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelBetween(Double value1, Double value2) {
            addCriterion("PDT_MAX_LEVEL between", value1, value2, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtMaxLevelNotBetween(Double value1, Double value2) {
            addCriterion("PDT_MAX_LEVEL not between", value1, value2, "pdtMaxLevel");
            return (Criteria) this;
        }

        public Criteria andPdtBpIsNull() {
            addCriterion("PDT_BP is null");
            return (Criteria) this;
        }

        public Criteria andPdtBpIsNotNull() {
            addCriterion("PDT_BP is not null");
            return (Criteria) this;
        }

        public Criteria andPdtBpEqualTo(BigDecimal value) {
            addCriterion("PDT_BP =", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpNotEqualTo(BigDecimal value) {
            addCriterion("PDT_BP <>", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpGreaterThan(BigDecimal value) {
            addCriterion("PDT_BP >", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_BP >=", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpLessThan(BigDecimal value) {
            addCriterion("PDT_BP <", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_BP <=", value, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpIn(List<BigDecimal> values) {
            addCriterion("PDT_BP in", values, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpNotIn(List<BigDecimal> values) {
            addCriterion("PDT_BP not in", values, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_BP between", value1, value2, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtBpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_BP not between", value1, value2, "pdtBp");
            return (Criteria) this;
        }

        public Criteria andPdtSpIsNull() {
            addCriterion("PDT_SP is null");
            return (Criteria) this;
        }

        public Criteria andPdtSpIsNotNull() {
            addCriterion("PDT_SP is not null");
            return (Criteria) this;
        }

        public Criteria andPdtSpEqualTo(BigDecimal value) {
            addCriterion("PDT_SP =", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpNotEqualTo(BigDecimal value) {
            addCriterion("PDT_SP <>", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpGreaterThan(BigDecimal value) {
            addCriterion("PDT_SP >", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_SP >=", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpLessThan(BigDecimal value) {
            addCriterion("PDT_SP <", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_SP <=", value, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpIn(List<BigDecimal> values) {
            addCriterion("PDT_SP in", values, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpNotIn(List<BigDecimal> values) {
            addCriterion("PDT_SP not in", values, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_SP between", value1, value2, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtSpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_SP not between", value1, value2, "pdtSp");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctIsNull() {
            addCriterion("PDT_PROFIT_PCT is null");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctIsNotNull() {
            addCriterion("PDT_PROFIT_PCT is not null");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctEqualTo(Double value) {
            addCriterion("PDT_PROFIT_PCT =", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctNotEqualTo(Double value) {
            addCriterion("PDT_PROFIT_PCT <>", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctGreaterThan(Double value) {
            addCriterion("PDT_PROFIT_PCT >", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctGreaterThanOrEqualTo(Double value) {
            addCriterion("PDT_PROFIT_PCT >=", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctLessThan(Double value) {
            addCriterion("PDT_PROFIT_PCT <", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctLessThanOrEqualTo(Double value) {
            addCriterion("PDT_PROFIT_PCT <=", value, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctIn(List<Double> values) {
            addCriterion("PDT_PROFIT_PCT in", values, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctNotIn(List<Double> values) {
            addCriterion("PDT_PROFIT_PCT not in", values, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctBetween(Double value1, Double value2) {
            addCriterion("PDT_PROFIT_PCT between", value1, value2, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtProfitPctNotBetween(Double value1, Double value2) {
            addCriterion("PDT_PROFIT_PCT not between", value1, value2, "pdtProfitPct");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdIsNull() {
            addCriterion("PDT_VAT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdIsNotNull() {
            addCriterion("PDT_VAT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdEqualTo(String value) {
            addCriterion("PDT_VAT_ID =", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdNotEqualTo(String value) {
            addCriterion("PDT_VAT_ID <>", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdGreaterThan(String value) {
            addCriterion("PDT_VAT_ID >", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_VAT_ID >=", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdLessThan(String value) {
            addCriterion("PDT_VAT_ID <", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdLessThanOrEqualTo(String value) {
            addCriterion("PDT_VAT_ID <=", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdLike(String value) {
            addCriterion("PDT_VAT_ID like", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdNotLike(String value) {
            addCriterion("PDT_VAT_ID not like", value, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdIn(List<String> values) {
            addCriterion("PDT_VAT_ID in", values, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdNotIn(List<String> values) {
            addCriterion("PDT_VAT_ID not in", values, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdBetween(String value1, String value2) {
            addCriterion("PDT_VAT_ID between", value1, value2, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtVatIdNotBetween(String value1, String value2) {
            addCriterion("PDT_VAT_ID not between", value1, value2, "pdtVatId");
            return (Criteria) this;
        }

        public Criteria andPdtStatusIsNull() {
            addCriterion("PDT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPdtStatusIsNotNull() {
            addCriterion("PDT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPdtStatusEqualTo(String value) {
            addCriterion("PDT_STATUS =", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusNotEqualTo(String value) {
            addCriterion("PDT_STATUS <>", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusGreaterThan(String value) {
            addCriterion("PDT_STATUS >", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_STATUS >=", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusLessThan(String value) {
            addCriterion("PDT_STATUS <", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusLessThanOrEqualTo(String value) {
            addCriterion("PDT_STATUS <=", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusLike(String value) {
            addCriterion("PDT_STATUS like", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusNotLike(String value) {
            addCriterion("PDT_STATUS not like", value, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusIn(List<String> values) {
            addCriterion("PDT_STATUS in", values, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusNotIn(List<String> values) {
            addCriterion("PDT_STATUS not in", values, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusBetween(String value1, String value2) {
            addCriterion("PDT_STATUS between", value1, value2, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStatusNotBetween(String value1, String value2) {
            addCriterion("PDT_STATUS not between", value1, value2, "pdtStatus");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthIsNull() {
            addCriterion("PDT_STRENGTH is null");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthIsNotNull() {
            addCriterion("PDT_STRENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthEqualTo(String value) {
            addCriterion("PDT_STRENGTH =", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthNotEqualTo(String value) {
            addCriterion("PDT_STRENGTH <>", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthGreaterThan(String value) {
            addCriterion("PDT_STRENGTH >", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_STRENGTH >=", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthLessThan(String value) {
            addCriterion("PDT_STRENGTH <", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthLessThanOrEqualTo(String value) {
            addCriterion("PDT_STRENGTH <=", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthLike(String value) {
            addCriterion("PDT_STRENGTH like", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthNotLike(String value) {
            addCriterion("PDT_STRENGTH not like", value, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthIn(List<String> values) {
            addCriterion("PDT_STRENGTH in", values, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthNotIn(List<String> values) {
            addCriterion("PDT_STRENGTH not in", values, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthBetween(String value1, String value2) {
            addCriterion("PDT_STRENGTH between", value1, value2, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtStrengthNotBetween(String value1, String value2) {
            addCriterion("PDT_STRENGTH not between", value1, value2, "pdtStrength");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyIsNull() {
            addCriterion("PDT_CURRENT_QTY is null");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyIsNotNull() {
            addCriterion("PDT_CURRENT_QTY is not null");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyEqualTo(Double value) {
            addCriterion("PDT_CURRENT_QTY =", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyNotEqualTo(Double value) {
            addCriterion("PDT_CURRENT_QTY <>", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyGreaterThan(Double value) {
            addCriterion("PDT_CURRENT_QTY >", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyGreaterThanOrEqualTo(Double value) {
            addCriterion("PDT_CURRENT_QTY >=", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyLessThan(Double value) {
            addCriterion("PDT_CURRENT_QTY <", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyLessThanOrEqualTo(Double value) {
            addCriterion("PDT_CURRENT_QTY <=", value, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyIn(List<Double> values) {
            addCriterion("PDT_CURRENT_QTY in", values, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyNotIn(List<Double> values) {
            addCriterion("PDT_CURRENT_QTY not in", values, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyBetween(Double value1, Double value2) {
            addCriterion("PDT_CURRENT_QTY between", value1, value2, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtCurrentQtyNotBetween(Double value1, Double value2) {
            addCriterion("PDT_CURRENT_QTY not between", value1, value2, "pdtCurrentQty");
            return (Criteria) this;
        }

        public Criteria andPdtAmountIsNull() {
            addCriterion("PDT_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPdtAmountIsNotNull() {
            addCriterion("PDT_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPdtAmountEqualTo(BigDecimal value) {
            addCriterion("PDT_AMOUNT =", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountNotEqualTo(BigDecimal value) {
            addCriterion("PDT_AMOUNT <>", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountGreaterThan(BigDecimal value) {
            addCriterion("PDT_AMOUNT >", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_AMOUNT >=", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountLessThan(BigDecimal value) {
            addCriterion("PDT_AMOUNT <", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PDT_AMOUNT <=", value, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountIn(List<BigDecimal> values) {
            addCriterion("PDT_AMOUNT in", values, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountNotIn(List<BigDecimal> values) {
            addCriterion("PDT_AMOUNT not in", values, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_AMOUNT between", value1, value2, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PDT_AMOUNT not between", value1, value2, "pdtAmount");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyIsNull() {
            addCriterion("PDT_OP_QTY is null");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyIsNotNull() {
            addCriterion("PDT_OP_QTY is not null");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyEqualTo(Double value) {
            addCriterion("PDT_OP_QTY =", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyNotEqualTo(Double value) {
            addCriterion("PDT_OP_QTY <>", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyGreaterThan(Double value) {
            addCriterion("PDT_OP_QTY >", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyGreaterThanOrEqualTo(Double value) {
            addCriterion("PDT_OP_QTY >=", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyLessThan(Double value) {
            addCriterion("PDT_OP_QTY <", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyLessThanOrEqualTo(Double value) {
            addCriterion("PDT_OP_QTY <=", value, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyIn(List<Double> values) {
            addCriterion("PDT_OP_QTY in", values, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyNotIn(List<Double> values) {
            addCriterion("PDT_OP_QTY not in", values, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyBetween(Double value1, Double value2) {
            addCriterion("PDT_OP_QTY between", value1, value2, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtOpQtyNotBetween(Double value1, Double value2) {
            addCriterion("PDT_OP_QTY not between", value1, value2, "pdtOpQty");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByIsNull() {
            addCriterion("PDT_DELETE_BY is null");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByIsNotNull() {
            addCriterion("PDT_DELETE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByEqualTo(String value) {
            addCriterion("PDT_DELETE_BY =", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByNotEqualTo(String value) {
            addCriterion("PDT_DELETE_BY <>", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByGreaterThan(String value) {
            addCriterion("PDT_DELETE_BY >", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByGreaterThanOrEqualTo(String value) {
            addCriterion("PDT_DELETE_BY >=", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByLessThan(String value) {
            addCriterion("PDT_DELETE_BY <", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByLessThanOrEqualTo(String value) {
            addCriterion("PDT_DELETE_BY <=", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByLike(String value) {
            addCriterion("PDT_DELETE_BY like", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByNotLike(String value) {
            addCriterion("PDT_DELETE_BY not like", value, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByIn(List<String> values) {
            addCriterion("PDT_DELETE_BY in", values, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByNotIn(List<String> values) {
            addCriterion("PDT_DELETE_BY not in", values, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByBetween(String value1, String value2) {
            addCriterion("PDT_DELETE_BY between", value1, value2, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteByNotBetween(String value1, String value2) {
            addCriterion("PDT_DELETE_BY not between", value1, value2, "pdtDeleteBy");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateIsNull() {
            addCriterion("PDT_DELETE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateIsNotNull() {
            addCriterion("PDT_DELETE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateEqualTo(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE =", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE <>", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateGreaterThan(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE >", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE >=", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateLessThan(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE <", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PDT_DELETE_DATE <=", value, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateIn(List<Date> values) {
            addCriterionForJDBCDate("PDT_DELETE_DATE in", values, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PDT_DELETE_DATE not in", values, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PDT_DELETE_DATE between", value1, value2, "pdtDeleteDate");
            return (Criteria) this;
        }

        public Criteria andPdtDeleteDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PDT_DELETE_DATE not between", value1, value2, "pdtDeleteDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_products
     *
     * @mbggenerated do_not_delete_during_merge Wed May 13 15:02:10 EAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_products
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}