package com.topline.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.topline.utils.GlobalCC;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_id
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private Integer purId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_invono
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private String purInvono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_refNo
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private String purRefno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_date
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private Date purDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_acc_code
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private Integer purAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_user
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private String purUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_status
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private String purStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_purchases.pur_posted_by
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    private String purPostedBy;
    private String _purAccCode;
    private Integer purLocCode;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_id
     *
     * @return the value of inv_purchases.pur_id
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public Integer getPurId() {
        return purId;
    }

    public Integer getPurLocCode() {
		return purLocCode;
	}

	public void setPurLocCode(Integer purLocCode) {
		this.purLocCode = purLocCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_id
     *
     * @param purId the value for inv_purchases.pur_id
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurId(Integer purId) {
        this.purId = purId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_invono
     *
     * @return the value of inv_purchases.pur_invono
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public String getPurInvono() {
        return purInvono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_invono
     *
     * @param purInvono the value for inv_purchases.pur_invono
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurInvono(String purInvono) {
        this.purInvono = purInvono == null ? null : purInvono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_refNo
     *
     * @return the value of inv_purchases.pur_refNo
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public String getPurRefno() {
        return purRefno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_refNo
     *
     * @param purRefno the value for inv_purchases.pur_refNo
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurRefno(String purRefno) {
        this.purRefno = purRefno == null ? null : purRefno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_date
     *
     * @return the value of inv_purchases.pur_date
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public Date getPurDate() {
        return purDate;
       
		
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_date
     *
     * @param purDate the value for inv_purchases.pur_date
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurDate(Date purDate) {
        this.purDate = purDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_acc_code
     *
     * @return the value of inv_purchases.pur_acc_code
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public Integer getPurAccCode() {
        return purAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_acc_code
     *
     * @param purAccCode the value for inv_purchases.pur_acc_code
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurAccCode(Integer purAccCode) {
        this.purAccCode = purAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_user
     *
     * @return the value of inv_purchases.pur_user
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public String getPurUser() {
        return purUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_user
     *
     * @param purUser the value for inv_purchases.pur_user
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurUser(String purUser) {
        this.purUser = purUser == null ? null : purUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_status
     *
     * @return the value of inv_purchases.pur_status
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public String getPurStatus() {
        return purStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_status
     *
     * @param purStatus the value for inv_purchases.pur_status
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurStatus(String purStatus) {
        this.purStatus = purStatus == null ? null : purStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_purchases.pur_posted_by
     *
     * @return the value of inv_purchases.pur_posted_by
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public String getPurPostedBy() {
        return purPostedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_purchases.pur_posted_by
     *
     * @param purPostedBy the value for inv_purchases.pur_posted_by
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    public void setPurPostedBy(String purPostedBy) {
        this.purPostedBy = purPostedBy == null ? null : purPostedBy.trim();
    }

	public String get_purAccCode() {
		return _purAccCode;
	}

	public void set_purAccCode(String _purAccCode) {
		this._purAccCode = _purAccCode;
	}
    
}