package com.topline.model;

import java.math.BigDecimal;
import java.util.Date;

public class SalePayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private Integer spymtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_inv_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private Integer spymtInvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_total
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private BigDecimal spymtTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_payMode
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private String spymtPaymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_payMethod
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private String spymtPaymethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_reference
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private String spymtReference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_amount_given
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private BigDecimal spymtAmountGiven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_change
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private BigDecimal spymtChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_done_by
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private String spymtDoneBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_sale_payment.spymt_date
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    private Date spymtDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_id
     *
     * @return the value of inv_sale_payment.spymt_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public Integer getSpymtId() {
        return spymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_id
     *
     * @param spymtId the value for inv_sale_payment.spymt_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtId(Integer spymtId) {
        this.spymtId = spymtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_inv_id
     *
     * @return the value of inv_sale_payment.spymt_inv_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public Integer getSpymtInvId() {
        return spymtInvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_inv_id
     *
     * @param spymtInvId the value for inv_sale_payment.spymt_inv_id
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtInvId(Integer spymtInvId) {
        this.spymtInvId = spymtInvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_total
     *
     * @return the value of inv_sale_payment.spymt_total
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public BigDecimal getSpymtTotal() {
        return spymtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_total
     *
     * @param spymtTotal the value for inv_sale_payment.spymt_total
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtTotal(BigDecimal spymtTotal) {
        this.spymtTotal = spymtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_payMode
     *
     * @return the value of inv_sale_payment.spymt_payMode
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public String getSpymtPaymode() {
        return spymtPaymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_payMode
     *
     * @param spymtPaymode the value for inv_sale_payment.spymt_payMode
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtPaymode(String spymtPaymode) {
        this.spymtPaymode = spymtPaymode == null ? null : spymtPaymode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_payMethod
     *
     * @return the value of inv_sale_payment.spymt_payMethod
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public String getSpymtPaymethod() {
        return spymtPaymethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_payMethod
     *
     * @param spymtPaymethod the value for inv_sale_payment.spymt_payMethod
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtPaymethod(String spymtPaymethod) {
        this.spymtPaymethod = spymtPaymethod == null ? null : spymtPaymethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_reference
     *
     * @return the value of inv_sale_payment.spymt_reference
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public String getSpymtReference() {
        return spymtReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_reference
     *
     * @param spymtReference the value for inv_sale_payment.spymt_reference
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtReference(String spymtReference) {
        this.spymtReference = spymtReference == null ? null : spymtReference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_amount_given
     *
     * @return the value of inv_sale_payment.spymt_amount_given
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public BigDecimal getSpymtAmountGiven() {
        return spymtAmountGiven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_amount_given
     *
     * @param spymtAmountGiven the value for inv_sale_payment.spymt_amount_given
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtAmountGiven(BigDecimal spymtAmountGiven) {
        this.spymtAmountGiven = spymtAmountGiven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_change
     *
     * @return the value of inv_sale_payment.spymt_change
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public BigDecimal getSpymtChange() {
        return spymtChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_change
     *
     * @param spymtChange the value for inv_sale_payment.spymt_change
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtChange(BigDecimal spymtChange) {
        this.spymtChange = spymtChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_done_by
     *
     * @return the value of inv_sale_payment.spymt_done_by
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public String getSpymtDoneBy() {
        return spymtDoneBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_done_by
     *
     * @param spymtDoneBy the value for inv_sale_payment.spymt_done_by
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtDoneBy(String spymtDoneBy) {
        this.spymtDoneBy = spymtDoneBy == null ? null : spymtDoneBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_sale_payment.spymt_date
     *
     * @return the value of inv_sale_payment.spymt_date
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public Date getSpymtDate() {
        return spymtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_sale_payment.spymt_date
     *
     * @param spymtDate the value for inv_sale_payment.spymt_date
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    public void setSpymtDate(Date spymtDate) {
        this.spymtDate = spymtDate;
    }
}