package com.topline.model;

public class TaskAssignee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_assignee.tssg_id
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    private Integer tssgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_assignee.tssg_name
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    private String tssgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_assignee.tssg_id
     *
     * @return the value of inv_task_assignee.tssg_id
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public Integer getTssgId() {
        return tssgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_assignee.tssg_id
     *
     * @param tssgId the value for inv_task_assignee.tssg_id
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void setTssgId(Integer tssgId) {
        this.tssgId = tssgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_assignee.tssg_name
     *
     * @return the value of inv_task_assignee.tssg_name
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public String getTssgName() {
        return tssgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_assignee.tssg_name
     *
     * @param tssgName the value for inv_task_assignee.tssg_name
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void setTssgName(String tssgName) {
        this.tssgName = tssgName == null ? null : tssgName.trim();
    }
}