package com.topline.model;

import java.util.ArrayList;
import java.util.List;

public class TaskAssigneeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public TaskAssigneeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTssgIdIsNull() {
            addCriterion("tssg_id is null");
            return (Criteria) this;
        }

        public Criteria andTssgIdIsNotNull() {
            addCriterion("tssg_id is not null");
            return (Criteria) this;
        }

        public Criteria andTssgIdEqualTo(Integer value) {
            addCriterion("tssg_id =", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdNotEqualTo(Integer value) {
            addCriterion("tssg_id <>", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdGreaterThan(Integer value) {
            addCriterion("tssg_id >", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tssg_id >=", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdLessThan(Integer value) {
            addCriterion("tssg_id <", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdLessThanOrEqualTo(Integer value) {
            addCriterion("tssg_id <=", value, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdIn(List<Integer> values) {
            addCriterion("tssg_id in", values, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdNotIn(List<Integer> values) {
            addCriterion("tssg_id not in", values, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdBetween(Integer value1, Integer value2) {
            addCriterion("tssg_id between", value1, value2, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tssg_id not between", value1, value2, "tssgId");
            return (Criteria) this;
        }

        public Criteria andTssgNameIsNull() {
            addCriterion("tssg_name is null");
            return (Criteria) this;
        }

        public Criteria andTssgNameIsNotNull() {
            addCriterion("tssg_name is not null");
            return (Criteria) this;
        }

        public Criteria andTssgNameEqualTo(String value) {
            addCriterion("tssg_name =", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameNotEqualTo(String value) {
            addCriterion("tssg_name <>", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameGreaterThan(String value) {
            addCriterion("tssg_name >", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameGreaterThanOrEqualTo(String value) {
            addCriterion("tssg_name >=", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameLessThan(String value) {
            addCriterion("tssg_name <", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameLessThanOrEqualTo(String value) {
            addCriterion("tssg_name <=", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameLike(String value) {
            addCriterion("tssg_name like", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameNotLike(String value) {
            addCriterion("tssg_name not like", value, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameIn(List<String> values) {
            addCriterion("tssg_name in", values, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameNotIn(List<String> values) {
            addCriterion("tssg_name not in", values, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameBetween(String value1, String value2) {
            addCriterion("tssg_name between", value1, value2, "tssgName");
            return (Criteria) this;
        }

        public Criteria andTssgNameNotBetween(String value1, String value2) {
            addCriterion("tssg_name not between", value1, value2, "tssgName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_task_assignee
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 27 03:11:17 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_task_assignee
     *
     * @mbggenerated Sat Aug 27 03:11:17 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}