package com.topline.model;

import java.math.BigDecimal;
import java.util.Date;

public class TaskDelivery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private Integer tskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private Date tskDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_acc_code
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private Integer tskAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_description
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private String tskDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_tssg_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private Integer tskTssgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_cost
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private BigDecimal tskCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_collection_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private Date tskCollectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_status
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private String tskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_task_delivery.tsk_remarks
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    private String tskRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_id
     *
     * @return the value of inv_task_delivery.tsk_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public Integer getTskId() {
        return tskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_id
     *
     * @param tskId the value for inv_task_delivery.tsk_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskId(Integer tskId) {
        this.tskId = tskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_date
     *
     * @return the value of inv_task_delivery.tsk_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public Date getTskDate() {
        return tskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_date
     *
     * @param tskDate the value for inv_task_delivery.tsk_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskDate(Date tskDate) {
        this.tskDate = tskDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_acc_code
     *
     * @return the value of inv_task_delivery.tsk_acc_code
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public Integer getTskAccCode() {
        return tskAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_acc_code
     *
     * @param tskAccCode the value for inv_task_delivery.tsk_acc_code
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskAccCode(Integer tskAccCode) {
        this.tskAccCode = tskAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_description
     *
     * @return the value of inv_task_delivery.tsk_description
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public String getTskDescription() {
        return tskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_description
     *
     * @param tskDescription the value for inv_task_delivery.tsk_description
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskDescription(String tskDescription) {
        this.tskDescription = tskDescription == null ? null : tskDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_tssg_id
     *
     * @return the value of inv_task_delivery.tsk_tssg_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public Integer getTskTssgId() {
        return tskTssgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_tssg_id
     *
     * @param tskTssgId the value for inv_task_delivery.tsk_tssg_id
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskTssgId(Integer tskTssgId) {
        this.tskTssgId = tskTssgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_cost
     *
     * @return the value of inv_task_delivery.tsk_cost
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public BigDecimal getTskCost() {
        return tskCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_cost
     *
     * @param tskCost the value for inv_task_delivery.tsk_cost
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskCost(BigDecimal tskCost) {
        this.tskCost = tskCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_collection_date
     *
     * @return the value of inv_task_delivery.tsk_collection_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public Date getTskCollectionDate() {
        return tskCollectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_collection_date
     *
     * @param tskCollectionDate the value for inv_task_delivery.tsk_collection_date
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskCollectionDate(Date tskCollectionDate) {
        this.tskCollectionDate = tskCollectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_status
     *
     * @return the value of inv_task_delivery.tsk_status
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public String getTskStatus() {
        return tskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_status
     *
     * @param tskStatus the value for inv_task_delivery.tsk_status
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskStatus(String tskStatus) {
        this.tskStatus = tskStatus == null ? null : tskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_task_delivery.tsk_remarks
     *
     * @return the value of inv_task_delivery.tsk_remarks
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public String getTskRemarks() {
        return tskRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_task_delivery.tsk_remarks
     *
     * @param tskRemarks the value for inv_task_delivery.tsk_remarks
     *
     * @mbggenerated Fri Sep 02 15:48:54 EAT 2016
     */
    public void setTskRemarks(String tskRemarks) {
        this.tskRemarks = tskRemarks == null ? null : tskRemarks.trim();
    }
}