package com.topline.model;

public class TransferDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_transfer_dtls.tnsfd_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    private Integer tnsfdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_transfer_dtls.tnsfd_tnsf_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    private Integer tnsfdTnsfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_transfer_dtls.tnsfd_pdt_code
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    private Integer tnsfdPdtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_transfer_dtls.tnsfd_qty
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    private Double tnsfdQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_transfer_dtls.tnsfd_stk_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    private Integer tnsfdStkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_transfer_dtls.tnsfd_id
     *
     * @return the value of inv_transfer_dtls.tnsfd_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Integer getTnsfdId() {
        return tnsfdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_transfer_dtls.tnsfd_id
     *
     * @param tnsfdId the value for inv_transfer_dtls.tnsfd_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setTnsfdId(Integer tnsfdId) {
        this.tnsfdId = tnsfdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_transfer_dtls.tnsfd_tnsf_id
     *
     * @return the value of inv_transfer_dtls.tnsfd_tnsf_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Integer getTnsfdTnsfId() {
        return tnsfdTnsfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_transfer_dtls.tnsfd_tnsf_id
     *
     * @param tnsfdTnsfId the value for inv_transfer_dtls.tnsfd_tnsf_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setTnsfdTnsfId(Integer tnsfdTnsfId) {
        this.tnsfdTnsfId = tnsfdTnsfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_transfer_dtls.tnsfd_pdt_code
     *
     * @return the value of inv_transfer_dtls.tnsfd_pdt_code
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Integer getTnsfdPdtCode() {
        return tnsfdPdtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_transfer_dtls.tnsfd_pdt_code
     *
     * @param tnsfdPdtCode the value for inv_transfer_dtls.tnsfd_pdt_code
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setTnsfdPdtCode(Integer tnsfdPdtCode) {
        this.tnsfdPdtCode = tnsfdPdtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_transfer_dtls.tnsfd_qty
     *
     * @return the value of inv_transfer_dtls.tnsfd_qty
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Double getTnsfdQty() {
        return tnsfdQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_transfer_dtls.tnsfd_qty
     *
     * @param tnsfdQty the value for inv_transfer_dtls.tnsfd_qty
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setTnsfdQty(Double tnsfdQty) {
        this.tnsfdQty = tnsfdQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_transfer_dtls.tnsfd_stk_id
     *
     * @return the value of inv_transfer_dtls.tnsfd_stk_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Integer getTnsfdStkId() {
        return tnsfdStkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_transfer_dtls.tnsfd_stk_id
     *
     * @param tnsfdStkId the value for inv_transfer_dtls.tnsfd_stk_id
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setTnsfdStkId(Integer tnsfdStkId) {
        this.tnsfdStkId = tnsfdStkId;
    }
}