package com.topline.model;

import java.util.ArrayList;
import java.util.List;

public class TransferDtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public TransferDtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTnsfdIdIsNull() {
            addCriterion("tnsfd_id is null");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdIsNotNull() {
            addCriterion("tnsfd_id is not null");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdEqualTo(Integer value) {
            addCriterion("tnsfd_id =", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdNotEqualTo(Integer value) {
            addCriterion("tnsfd_id <>", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdGreaterThan(Integer value) {
            addCriterion("tnsfd_id >", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_id >=", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdLessThan(Integer value) {
            addCriterion("tnsfd_id <", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdLessThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_id <=", value, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdIn(List<Integer> values) {
            addCriterion("tnsfd_id in", values, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdNotIn(List<Integer> values) {
            addCriterion("tnsfd_id not in", values, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_id between", value1, value2, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_id not between", value1, value2, "tnsfdId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdIsNull() {
            addCriterion("tnsfd_tnsf_id is null");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdIsNotNull() {
            addCriterion("tnsfd_tnsf_id is not null");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdEqualTo(Integer value) {
            addCriterion("tnsfd_tnsf_id =", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdNotEqualTo(Integer value) {
            addCriterion("tnsfd_tnsf_id <>", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdGreaterThan(Integer value) {
            addCriterion("tnsfd_tnsf_id >", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_tnsf_id >=", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdLessThan(Integer value) {
            addCriterion("tnsfd_tnsf_id <", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdLessThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_tnsf_id <=", value, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdIn(List<Integer> values) {
            addCriterion("tnsfd_tnsf_id in", values, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdNotIn(List<Integer> values) {
            addCriterion("tnsfd_tnsf_id not in", values, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_tnsf_id between", value1, value2, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdTnsfIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_tnsf_id not between", value1, value2, "tnsfdTnsfId");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeIsNull() {
            addCriterion("tnsfd_pdt_code is null");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeIsNotNull() {
            addCriterion("tnsfd_pdt_code is not null");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeEqualTo(Integer value) {
            addCriterion("tnsfd_pdt_code =", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeNotEqualTo(Integer value) {
            addCriterion("tnsfd_pdt_code <>", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeGreaterThan(Integer value) {
            addCriterion("tnsfd_pdt_code >", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_pdt_code >=", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeLessThan(Integer value) {
            addCriterion("tnsfd_pdt_code <", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeLessThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_pdt_code <=", value, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeIn(List<Integer> values) {
            addCriterion("tnsfd_pdt_code in", values, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeNotIn(List<Integer> values) {
            addCriterion("tnsfd_pdt_code not in", values, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_pdt_code between", value1, value2, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdPdtCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_pdt_code not between", value1, value2, "tnsfdPdtCode");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyIsNull() {
            addCriterion("tnsfd_qty is null");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyIsNotNull() {
            addCriterion("tnsfd_qty is not null");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyEqualTo(Double value) {
            addCriterion("tnsfd_qty =", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyNotEqualTo(Double value) {
            addCriterion("tnsfd_qty <>", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyGreaterThan(Double value) {
            addCriterion("tnsfd_qty >", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyGreaterThanOrEqualTo(Double value) {
            addCriterion("tnsfd_qty >=", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyLessThan(Double value) {
            addCriterion("tnsfd_qty <", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyLessThanOrEqualTo(Double value) {
            addCriterion("tnsfd_qty <=", value, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyIn(List<Double> values) {
            addCriterion("tnsfd_qty in", values, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyNotIn(List<Double> values) {
            addCriterion("tnsfd_qty not in", values, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyBetween(Double value1, Double value2) {
            addCriterion("tnsfd_qty between", value1, value2, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdQtyNotBetween(Double value1, Double value2) {
            addCriterion("tnsfd_qty not between", value1, value2, "tnsfdQty");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdIsNull() {
            addCriterion("tnsfd_stk_id is null");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdIsNotNull() {
            addCriterion("tnsfd_stk_id is not null");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdEqualTo(Integer value) {
            addCriterion("tnsfd_stk_id =", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdNotEqualTo(Integer value) {
            addCriterion("tnsfd_stk_id <>", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdGreaterThan(Integer value) {
            addCriterion("tnsfd_stk_id >", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_stk_id >=", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdLessThan(Integer value) {
            addCriterion("tnsfd_stk_id <", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdLessThanOrEqualTo(Integer value) {
            addCriterion("tnsfd_stk_id <=", value, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdIn(List<Integer> values) {
            addCriterion("tnsfd_stk_id in", values, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdNotIn(List<Integer> values) {
            addCriterion("tnsfd_stk_id not in", values, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_stk_id between", value1, value2, "tnsfdStkId");
            return (Criteria) this;
        }

        public Criteria andTnsfdStkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tnsfd_stk_id not between", value1, value2, "tnsfdStkId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 04 19:48:27 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}