package com.topline.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserLocationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public UserLocationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUslocCodeIsNull() {
            addCriterion("usloc_code is null");
            return (Criteria) this;
        }

        public Criteria andUslocCodeIsNotNull() {
            addCriterion("usloc_code is not null");
            return (Criteria) this;
        }

        public Criteria andUslocCodeEqualTo(Integer value) {
            addCriterion("usloc_code =", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeNotEqualTo(Integer value) {
            addCriterion("usloc_code <>", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeGreaterThan(Integer value) {
            addCriterion("usloc_code >", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("usloc_code >=", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeLessThan(Integer value) {
            addCriterion("usloc_code <", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeLessThanOrEqualTo(Integer value) {
            addCriterion("usloc_code <=", value, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeIn(List<Integer> values) {
            addCriterion("usloc_code in", values, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeNotIn(List<Integer> values) {
            addCriterion("usloc_code not in", values, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeBetween(Integer value1, Integer value2) {
            addCriterion("usloc_code between", value1, value2, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("usloc_code not between", value1, value2, "uslocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeIsNull() {
            addCriterion("usloc_loc_code is null");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeIsNotNull() {
            addCriterion("usloc_loc_code is not null");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeEqualTo(Integer value) {
            addCriterion("usloc_loc_code =", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeNotEqualTo(Integer value) {
            addCriterion("usloc_loc_code <>", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeGreaterThan(Integer value) {
            addCriterion("usloc_loc_code >", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("usloc_loc_code >=", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeLessThan(Integer value) {
            addCriterion("usloc_loc_code <", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeLessThanOrEqualTo(Integer value) {
            addCriterion("usloc_loc_code <=", value, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeIn(List<Integer> values) {
            addCriterion("usloc_loc_code in", values, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeNotIn(List<Integer> values) {
            addCriterion("usloc_loc_code not in", values, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeBetween(Integer value1, Integer value2) {
            addCriterion("usloc_loc_code between", value1, value2, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocLocCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("usloc_loc_code not between", value1, value2, "uslocLocCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeIsNull() {
            addCriterion("usloc_usr_code is null");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeIsNotNull() {
            addCriterion("usloc_usr_code is not null");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeEqualTo(Integer value) {
            addCriterion("usloc_usr_code =", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeNotEqualTo(Integer value) {
            addCriterion("usloc_usr_code <>", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeGreaterThan(Integer value) {
            addCriterion("usloc_usr_code >", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("usloc_usr_code >=", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeLessThan(Integer value) {
            addCriterion("usloc_usr_code <", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeLessThanOrEqualTo(Integer value) {
            addCriterion("usloc_usr_code <=", value, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeIn(List<Integer> values) {
            addCriterion("usloc_usr_code in", values, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeNotIn(List<Integer> values) {
            addCriterion("usloc_usr_code not in", values, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeBetween(Integer value1, Integer value2) {
            addCriterion("usloc_usr_code between", value1, value2, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUsrCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("usloc_usr_code not between", value1, value2, "uslocUsrCode");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByIsNull() {
            addCriterion("usloc_updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByIsNotNull() {
            addCriterion("usloc_updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByEqualTo(String value) {
            addCriterion("usloc_updated_by =", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByNotEqualTo(String value) {
            addCriterion("usloc_updated_by <>", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByGreaterThan(String value) {
            addCriterion("usloc_updated_by >", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("usloc_updated_by >=", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByLessThan(String value) {
            addCriterion("usloc_updated_by <", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("usloc_updated_by <=", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByLike(String value) {
            addCriterion("usloc_updated_by like", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByNotLike(String value) {
            addCriterion("usloc_updated_by not like", value, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByIn(List<String> values) {
            addCriterion("usloc_updated_by in", values, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByNotIn(List<String> values) {
            addCriterion("usloc_updated_by not in", values, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByBetween(String value1, String value2) {
            addCriterion("usloc_updated_by between", value1, value2, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedByNotBetween(String value1, String value2) {
            addCriterion("usloc_updated_by not between", value1, value2, "uslocUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnIsNull() {
            addCriterion("usloc_updated_on is null");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnIsNotNull() {
            addCriterion("usloc_updated_on is not null");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnEqualTo(Date value) {
            addCriterion("usloc_updated_on =", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnNotEqualTo(Date value) {
            addCriterion("usloc_updated_on <>", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnGreaterThan(Date value) {
            addCriterion("usloc_updated_on >", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnGreaterThanOrEqualTo(Date value) {
            addCriterion("usloc_updated_on >=", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnLessThan(Date value) {
            addCriterion("usloc_updated_on <", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnLessThanOrEqualTo(Date value) {
            addCriterion("usloc_updated_on <=", value, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnIn(List<Date> values) {
            addCriterion("usloc_updated_on in", values, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnNotIn(List<Date> values) {
            addCriterion("usloc_updated_on not in", values, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnBetween(Date value1, Date value2) {
            addCriterion("usloc_updated_on between", value1, value2, "uslocUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andUslocUpdatedOnNotBetween(Date value1, Date value2) {
            addCriterion("usloc_updated_on not between", value1, value2, "uslocUpdatedOn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_user_locations
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 23 00:07:14 EAT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}