package com.topline.model;

import java.util.Date;

public class Vat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_vat.VAT_ID
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    private String vatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_vat.VAT_RATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    private Double vatRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inv_vat.VAT_DATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    private Date vatDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_vat.VAT_ID
     *
     * @return the value of inv_vat.VAT_ID
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public String getVatId() {
        return vatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_vat.VAT_ID
     *
     * @param vatId the value for inv_vat.VAT_ID
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void setVatId(String vatId) {
        this.vatId = vatId == null ? null : vatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_vat.VAT_RATE
     *
     * @return the value of inv_vat.VAT_RATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public Double getVatRate() {
        return vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_vat.VAT_RATE
     *
     * @param vatRate the value for inv_vat.VAT_RATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void setVatRate(Double vatRate) {
        this.vatRate = vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inv_vat.VAT_DATE
     *
     * @return the value of inv_vat.VAT_DATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public Date getVatDate() {
        return vatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inv_vat.VAT_DATE
     *
     * @param vatDate the value for inv_vat.VAT_DATE
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    public void setVatDate(Date vatDate) {
        this.vatDate = vatDate;
    }
}