package com.topline.mappers;

import com.topline.model.Account;
import com.topline.model.AccountExample;
import com.topline.model.wrappers.PurchaseWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int deleteByPrimaryKey(Integer accCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    Account selectByPrimaryKey(Integer accCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_accounts
     *
     * @mbggenerated Fri Jul 24 21:41:34 EAT 2015
     */
    int updateByPrimaryKey(Account record);
    List<Account> fetchAccounts(Map<String,Object> map);
}