package com.topline.mappers;

import com.topline.model.ApprovalAreaDtl;
import com.topline.model.ApprovalAreaDtlExample;
import com.topline.model.wrappers.ApprovalAreaDtlWrapper;
import com.topline.model.wrappers.SystemAreasWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ApprovalAreaDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int countByExample(ApprovalAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int deleteByExample(ApprovalAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int deleteByPrimaryKey(Integer appvdCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int insert(ApprovalAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int insertSelective(ApprovalAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    List<ApprovalAreaDtl> selectByExample(ApprovalAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    ApprovalAreaDtl selectByPrimaryKey(Integer appvdCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ApprovalAreaDtl record, @Param("example") ApprovalAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int updateByExample(@Param("record") ApprovalAreaDtl record, @Param("example") ApprovalAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int updateByPrimaryKeySelective(ApprovalAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_approval_dtls
     *
     * @mbggenerated Sun Aug 14 22:31:54 EAT 2016
     */
    int updateByPrimaryKey(ApprovalAreaDtl record);
    //add methods
    List<ApprovalAreaDtlWrapper>fetchApprovalAreas(Map<String,Object> map);
}