package com.topline.mappers;

import com.topline.model.Categories;
import com.topline.model.CategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByPrimaryKey(Integer catCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    Categories selectByPrimaryKey(Integer catCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExample(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_categories
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKey(Categories record);
}