package com.topline.mappers;

import com.topline.model.CustomizeArea;
import com.topline.model.CustomizeAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomizeAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int countByExample(CustomizeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int deleteByExample(CustomizeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int deleteByPrimaryKey(String ctaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int insert(CustomizeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int insertSelective(CustomizeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    List<CustomizeArea> selectByExample(CustomizeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    CustomizeArea selectByPrimaryKey(String ctaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByExampleSelective(@Param("record") CustomizeArea record, @Param("example") CustomizeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByExample(@Param("record") CustomizeArea record, @Param("example") CustomizeAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByPrimaryKeySelective(CustomizeArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByPrimaryKey(CustomizeArea record);
}