package com.topline.mappers;

import com.topline.model.CustomizeAreaDtl;
import com.topline.model.CustomizeAreaDtlExample;
import com.topline.model.wrappers.SystemAreasWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CustomizeAreaDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int countByExample(CustomizeAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int deleteByExample(CustomizeAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int deleteByPrimaryKey(Integer ctadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int insert(CustomizeAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int insertSelective(CustomizeAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    List<CustomizeAreaDtl> selectByExample(CustomizeAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    CustomizeAreaDtl selectByPrimaryKey(Integer ctadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByExampleSelective(@Param("record") CustomizeAreaDtl record, @Param("example") CustomizeAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByExample(@Param("record") CustomizeAreaDtl record, @Param("example") CustomizeAreaDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByPrimaryKeySelective(CustomizeAreaDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_customize_areas_dtls
     *
     * @mbggenerated Fri May 13 19:27:13 EAT 2016
     */
    int updateByPrimaryKey(CustomizeAreaDtl record);
    
    //add methods
    List<SystemAreasWrapper>fetchSystemAreas(Map<String,Object> map);
}