package com.topline.mappers;

import com.topline.model.Invoice;
import com.topline.model.InvoiceExample;
import com.topline.model.wrappers.InvoiceWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int countByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int deleteByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int deleteByPrimaryKey(Integer invId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    Invoice selectByPrimaryKey(Integer invId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int updateByExample(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_invoices
     *
     * @mbggenerated Tue Oct 27 17:10:02 EAT 2015
     */
    int updateByPrimaryKey(Invoice record);
  //add methods
    int save(Invoice record);
    List<InvoiceWrapper> fetchInvoices(Map<String,Object> map);
    String fetchInvoiceNumber(Map<String,Object> map);
    int updateNextInvoiceNumber(Map<String,Object> map);
}