package com.topline.mappers;

import com.topline.model.ItemDiscrepancy;
import com.topline.model.ItemDiscrepancyExample;
import com.topline.model.ItemReturn;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ItemDiscrepancyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int countByExample(ItemDiscrepancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByExample(ItemDiscrepancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByPrimaryKey(Integer dscId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insert(ItemDiscrepancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insertSelective(ItemDiscrepancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    List<ItemDiscrepancy> selectByExample(ItemDiscrepancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    ItemDiscrepancy selectByPrimaryKey(Integer dscId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ItemDiscrepancy record, @Param("example") ItemDiscrepancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExample(@Param("record") ItemDiscrepancy record, @Param("example") ItemDiscrepancyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKeySelective(ItemDiscrepancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKey(ItemDiscrepancy record);
  //added methods
    int save(ItemDiscrepancy record);
}