package com.topline.mappers;

import com.topline.model.ItemSwap;
import com.topline.model.ItemSwapExample;
import com.topline.model.wrappers.ItemSwapWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ItemSwapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int countByExample(ItemSwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int deleteByExample(ItemSwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int deleteByPrimaryKey(Integer swpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int insert(ItemSwap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int insertSelective(ItemSwap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    List<ItemSwap> selectByExample(ItemSwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    ItemSwap selectByPrimaryKey(Integer swpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ItemSwap record, @Param("example") ItemSwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByExample(@Param("record") ItemSwap record, @Param("example") ItemSwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByPrimaryKeySelective(ItemSwap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_item_swap
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByPrimaryKey(ItemSwap record);
    //added methods
    int save(ItemSwap record);
    List<ItemSwapWrapper> fetchSwapM(Map<String,Object> map);
    Object postSwap(Map<String,Object> map);
}