package com.topline.mappers;

import com.topline.model.ItemReturnDtl;
import com.topline.model.ItemReturnDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemReturnDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int countByExample(ItemReturnDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByExample(ItemReturnDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByPrimaryKey(Integer rtndId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insert(ItemReturnDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insertSelective(ItemReturnDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    List<ItemReturnDtl> selectByExample(ItemReturnDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    ItemReturnDtl selectByPrimaryKey(Integer rtndId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ItemReturnDtl record, @Param("example") ItemReturnDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExample(@Param("record") ItemReturnDtl record, @Param("example") ItemReturnDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKeySelective(ItemReturnDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKey(ItemReturnDtl record);
}