package com.topline.mappers;

import com.topline.model.ItemDiscrepancyDtl;
import com.topline.model.ItemDiscrepancyDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemDiscrepancyDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int countByExample(ItemDiscrepancyDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByExample(ItemDiscrepancyDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int deleteByPrimaryKey(Integer dscdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insert(ItemDiscrepancyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int insertSelective(ItemDiscrepancyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    List<ItemDiscrepancyDtl> selectByExample(ItemDiscrepancyDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    ItemDiscrepancyDtl selectByPrimaryKey(Integer dscdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ItemDiscrepancyDtl record, @Param("example") ItemDiscrepancyDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByExample(@Param("record") ItemDiscrepancyDtl record, @Param("example") ItemDiscrepancyDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKeySelective(ItemDiscrepancyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_discrepancies_dtls
     *
     * @mbggenerated Mon Aug 01 16:35:05 EAT 2016
     */
    int updateByPrimaryKey(ItemDiscrepancyDtl record);
}