package com.topline.mappers;

import com.topline.model.ItemReturn;
import com.topline.model.ItemReturnExample;
import com.topline.model.wrappers.ItemReturnWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ItemReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int countByExample(ItemReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int deleteByExample(ItemReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int deleteByPrimaryKey(Integer rtnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int insert(ItemReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int insertSelective(ItemReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    List<ItemReturn> selectByExample(ItemReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    ItemReturn selectByPrimaryKey(Integer rtnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ItemReturn record, @Param("example") ItemReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByExample(@Param("record") ItemReturn record, @Param("example") ItemReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByPrimaryKeySelective(ItemReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_returns
     *
     * @mbggenerated Fri Oct 28 12:52:19 EAT 2016
     */
    int updateByPrimaryKey(ItemReturn record);
	 //added methods
    int save(ItemReturn record);
    List<ItemReturnWrapper> fetchReturnM(Map<String,Object> map);
    Object postReturns(Map<String,Object> map);
}