package com.topline.mappers;

import com.topline.model.Locations;
import com.topline.model.LocationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int countByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByPrimaryKey(Integer locCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insert(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insertSelective(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    List<Locations> selectByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    Locations selectByPrimaryKey(Integer locCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Locations record, @Param("example") LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExample(@Param("record") Locations record, @Param("example") LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKeySelective(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKey(Locations record);
}