package com.topline.mappers;

import com.topline.model.ManAdjustmentDtl;
import com.topline.model.ManAdjustmentDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManAdjustmentDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int countByExample(ManAdjustmentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int deleteByExample(ManAdjustmentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int deleteByPrimaryKey(Integer madjdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int insert(ManAdjustmentDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int insertSelective(ManAdjustmentDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    List<ManAdjustmentDtl> selectByExample(ManAdjustmentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    ManAdjustmentDtl selectByPrimaryKey(Integer madjdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int updateByExampleSelective(@Param("record") ManAdjustmentDtl record, @Param("example") ManAdjustmentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int updateByExample(@Param("record") ManAdjustmentDtl record, @Param("example") ManAdjustmentDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int updateByPrimaryKeySelective(ManAdjustmentDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_man_adjustment_dtls
     *
     * @mbggenerated Sat Apr 09 20:36:27 EAT 2016
     */
    int updateByPrimaryKey(ManAdjustmentDtl record);
}