package com.topline.mappers;

import com.topline.model.Purchase;
import com.topline.model.PurchaseExample;
import com.topline.model.wrappers.PurchaseWrapper;
import com.topline.model.wrappers.SubLocationWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int countByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int deleteByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int deleteByPrimaryKey(Integer purId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int insertSelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    List<Purchase> selectByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    Purchase selectByPrimaryKey(Integer purId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int updateByExample(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int updateByPrimaryKeySelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_purchases
     *
     * @mbggenerated Thu Jul 23 15:43:34 EAT 2015
     */
    int updateByPrimaryKey(Purchase record);
  //add methods
    int save(Purchase record);  
    List<PurchaseWrapper> fetchPurchases(Map<String,Object> map);
}