package com.topline.mappers;

import com.topline.model.SalePayment;
import com.topline.model.SalePaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalePaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int countByExample(SalePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int deleteByExample(SalePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int deleteByPrimaryKey(Integer spymtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int insert(SalePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int insertSelective(SalePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    List<SalePayment> selectByExample(SalePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    SalePayment selectByPrimaryKey(Integer spymtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int updateByExampleSelective(@Param("record") SalePayment record, @Param("example") SalePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int updateByExample(@Param("record") SalePayment record, @Param("example") SalePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int updateByPrimaryKeySelective(SalePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sale_payment
     *
     * @mbggenerated Tue Sep 06 15:47:38 EAT 2016
     */
    int updateByPrimaryKey(SalePayment record);
}