package com.topline.mappers;

import com.topline.model.SubLocations;
import com.topline.model.SubLocationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubLocationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int countByExample(SubLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByExample(SubLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int deleteByPrimaryKey(Integer slocCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insert(SubLocations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int insertSelective(SubLocations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    List<SubLocations> selectByExample(SubLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    SubLocations selectByPrimaryKey(Integer slocCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExampleSelective(@Param("record") SubLocations record, @Param("example") SubLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByExample(@Param("record") SubLocations record, @Param("example") SubLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKeySelective(SubLocations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_sub_locations
     *
     * @mbggenerated Wed May 13 15:02:10 EAT 2015
     */
    int updateByPrimaryKey(SubLocations record);
}