package com.topline.mappers;

import com.topline.model.Transfer;
import com.topline.model.TransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int countByExample(TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int deleteByExample(TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int deleteByPrimaryKey(Integer tnsfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int insert(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int insertSelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    List<Transfer> selectByExample(TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    Transfer selectByPrimaryKey(Integer tnsfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByExampleSelective(@Param("record") Transfer record, @Param("example") TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByExample(@Param("record") Transfer record, @Param("example") TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByPrimaryKeySelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfers
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByPrimaryKey(Transfer record);
}