package com.topline.mappers;

import com.topline.model.TransferDtl;
import com.topline.model.TransferDtlExample;
import com.topline.model.wrappers.PurchaseDetailWrapper;
import com.topline.model.wrappers.TransferDtlWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TransferDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int countByExample(TransferDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int deleteByExample(TransferDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int deleteByPrimaryKey(Integer tnsfdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int insert(TransferDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int insertSelective(TransferDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    List<TransferDtl> selectByExample(TransferDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    TransferDtl selectByPrimaryKey(Integer tnsfdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByExampleSelective(@Param("record") TransferDtl record, @Param("example") TransferDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByExample(@Param("record") TransferDtl record, @Param("example") TransferDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByPrimaryKeySelective(TransferDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_transfer_dtls
     *
     * @mbggenerated Thu Feb 04 19:48:27 EAT 2016
     */
    int updateByPrimaryKey(TransferDtl record);
    List<TransferDtlWrapper> fetchRptTransfers(Map<String,Object> map);
}