package com.topline.mappers;

import com.topline.model.UserLocation;
import com.topline.model.UserLocationExample;
import com.topline.model.wrappers.UserLocationWrapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int countByExample(UserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int deleteByExample(UserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int deleteByPrimaryKey(Integer uslocCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int insert(UserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int insertSelective(UserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    List<UserLocation> selectByExample(UserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    UserLocation selectByPrimaryKey(Integer uslocCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int updateByExampleSelective(@Param("record") UserLocation record, @Param("example") UserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int updateByExample(@Param("record") UserLocation record, @Param("example") UserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int updateByPrimaryKeySelective(UserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_user_locations
     *
     * @mbggenerated Fri Sep 23 00:07:14 EAT 2016
     */
    int updateByPrimaryKey(UserLocation record);
    
  //add methods
    List<UserLocationWrapper>fetchUserLocations(Map<String,Object> map);
    List<UserLocationWrapper>fetchAssignedUserLocations(Map<String,Object> map);
    
}