package com.topline.mappers;

import com.topline.model.Vat;
import com.topline.model.VatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int countByExample(VatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int deleteByExample(VatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int deleteByPrimaryKey(String vatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int insert(Vat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int insertSelective(Vat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    List<Vat> selectByExample(VatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    Vat selectByPrimaryKey(String vatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int updateByExampleSelective(@Param("record") Vat record, @Param("example") VatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int updateByExample(@Param("record") Vat record, @Param("example") VatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int updateByPrimaryKeySelective(Vat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_vat
     *
     * @mbggenerated Mon Sep 19 15:13:09 EAT 2016
     */
    int updateByPrimaryKey(Vat record);
}