CREATE TABLE `inv_products` (
  `pdt_code` int(11) NOT NULL,
  `pdt_sht_desc` varchar(50) DEFAULT NULL,
  `pdt_description` varchar(250) NOT NULL,
  `pdt_loc_code` int(11) DEFAULT NULL,
  `pdt_sloc_code` int(11) DEFAULT NULL,
  `pdt_cat_code` int(11) DEFAULT NULL,
  `pdt_min_level` double DEFAULT '0',
  `pdt_max_level` double NOT NULL DEFAULT '0',
  `pdt_bp` decimal(14,2) NOT NULL DEFAULT '0.00',
  `pdt_sp` decimal(14,2) DEFAULT '0.00',
  `pdt_profit_pct` double DEFAULT NULL,
  `pdt_vat_id` varchar(1) NOT NULL,
  `pdt_status` varchar(45) NOT NULL DEFAULT 'ACTIVE',
  `pdt_strength` varchar(20) DEFAULT NULL,
  `pdt_current_qty` double NOT NULL DEFAULT '0',
  `pdt_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `pdt_op_qty` double DEFAULT NULL,
  `pdt_delete_by` varchar(50) DEFAULT NULL,
  `pdt_delete_date` date DEFAULT NULL,
  PRIMARY KEY (`PDT_CODE`),
  KEY `pdt_loc_code_fk` (`pdt_loc_code`),
  KEY `pdt_sloc_code_fk` (`pdt_sloc_code`),
  KEY `pdt_cat_code_fk` (`pdt_cat_code`),
  KEY `pdt_vat_id_fk` (`pdt_vat_id`),
  CONSTRAINT `pdt_cat_code_fk` FOREIGN KEY (`pdt_cat_code`) REFERENCES `inv_categories` (`cat_code`),
  CONSTRAINT `pdt_loc_code_fk` FOREIGN KEY (`pdt_loc_code`) REFERENCES `inv_locations` (`loc_code`),
  CONSTRAINT `pdt_sloc_code_fk` FOREIGN KEY (`pdt_sloc_code`) REFERENCES `inv_sub_locations` (`sloc_code`),
  CONSTRAINT `pdt_vat_id_fk` FOREIGN KEY (`pdt_vat_id`) REFERENCES `inv_vat` (`vat_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
